### ISSUE TITLE
Add `semicolon` option

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/xo#1]
Would love to be able to turn off the requirement of semicolons. (I like all the other rules, including tabs, so I can't use feross/standard)

Is this planned/would a PR be accepted?

**Comment by sindresorhus** [comment]
The whole point of this module is to be opinionated. I added the `space` option only for pragmatic reasons as I want to use `xo` in projects that requires 2-space indent. I'll think about it though :)

**Comment by markogresak** [comment]
What's the point of having another opinionated code style, aren't there enough already? Same as with spaces/tabs, not everyone works on a project with semicolons everywhere in the code, although I agree with your point made in readme. 
I really love the simplicity part, but being so opinionated won't get this linter the reach it deserves.

My suggestion is have default options and enforce those and strongly suggest their usage, but leave room for people who would love to use this linter, but can't adapt it to their current project sources.

**Comment by sindresorhus** [comment]
Yeah, I'm going to add a `rules` option to override rules. I need it too for some projects and I don't want to have to specify the rule overrides in each file.

**Comment by jeromedecoster** [comment]
:+1: for configurable semicolons, thanks

**Comment by sindresorhus** [comment]
In 0.5.0 you can enforce no semicolons by putting this in package.json:

```json
{
  "xo": {
    "rules": {
      "semi": [2, "never"]
    }
  }
}
```

I might consider a `{"semicolon": false}` option in the future, for simplicity, if the demand is high enough. (Meaning :+1: here if you want that).

**Comment by jeromedecoster** [comment]
:+1:  to `{"semicolon": false}`

**Comment by ArtskydJ** [comment]
:+1: to `{"semicolon": false}`

**Comment by TehShrike** [comment]
:+1: to {"semicolon": false}

**Comment by mattdesl** [comment]
I think there's some other rules that should get turned on when `semicolon: false`, aren't there? If so, then :+1: to a flag that turns on all those safeguards.

**Comment by sindresorhus** [comment]
> I think there's some other rules that should get turned on when semicolon: false, aren't there?

Which ones?
