### ISSUE TITLE
Getters/setters bark about spacing

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/xo#10]
```javascript
var obj = {
  get something() {
  }
};
```

Gets me this cryptic error:

```
19:3  error  Expected indentation of 1 characters but found 0  indent
```

**Comment by Qix-** [comment]
Nevermind; I'm converting an existing project over to XO and it's space-indented :) Might want a better error message for it.

**Comment by kevva** [comment]
Yeah, that's coming from eslint.

**Comment by Qix-** [comment]
Figured as much. Maybe this issue will help someone else in the future :+1:

**Comment by sindresorhus** [comment]
@Qix- I've been confused by that error message multiple times too. I've opened an ESLint issue about improving it: https://github.com/eslint/eslint/issues/3340

**Comment by Qix-** [comment]
Awesome, glad to know I'm not the only one.
