### ISSUE TITLE
`optionsManager.buildConfig` only includes some options

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#101]
It's filtering out many options, like `cwd`, `filename`, etc.

I had to work around it [here](https://github.com/sindresorhus/xo/blob/9fce4fb1a59abb28a47b2bbbc0ce3d922eb163ab/index.js#L8), but would like to know the reason for it being like that. @jamestalmage ?
## 

Probably one of the reasons for https://github.com/sindresorhus/atom-linter-xo/issues/19

**Comment by jamestalmage** [comment]
I have strong suspicions it is related to https://github.com/sindresorhus/deep-assign/issues/6

**Comment by sindresorhus** [comment]
@jamestalmage I don't think so. I explicitly use v1 of deep-assign, not v2 as mentioned there: https://github.com/sindresorhus/xo/blob/9fce4fb1a59abb28a47b2bbbc0ce3d922eb163ab/package.json#L67

**Comment by jamestalmage** [comment]
Hmm.

Looking at the code, I don't see any reason `cwd` and `filename` wouldn't be copied.

Is it only affecting `lintText`?

**Comment by sindresorhus** [comment]
> Looking at the code, I don't see any reason cwd and filename wouldn't be copied.

You explicitly pluck out only some of the options here: https://github.com/sindresorhus/xo/blob/9fce4fb1a59abb28a47b2bbbc0ce3d922eb163ab/options-manager.js#L78-L82

> Is it only affecting lintText?

Not sure. That's where I noticed it.

**Comment by jamestalmage** [comment]
Why on earth did I do that?

**Comment by marionebl** [comment]
Fixed since 3621ac5923afef15fd8f051518a688c8d6d1cb30
