### ISSUE TITLE
i might suggest that not caring about code style or formatting is a better way to go

### ISSUE THREAD

**Issue by govpack** [sindresorhus/xo#11]
i might suggest that not caring about code style/formatting is a better way to go
why people get so hung up on something so pointless i would not know
code is a big messy garden/wilderness
so many people will do it so many ways
parser doesn't care, why should i? i don't uses spaces or tabs
what do they do? why even bother typing them in
if you are reading code you are kind of lost
readability and maintainability is a myth
who cares less -- wins

**Comment by sindresorhus** [comment]
ok
