### ISSUE TITLE
Esnext should default to true, pay attention to false

### ISSUE THREAD

**Issue by lukeed** [sindresorhus/xo#110]
As [noted here](https://github.com/sindresorhus/xo/blob/9a6513b72b201f2c7051850374127b3cee25db0c/config/overrides.js#L3), what if you actually _want_ ES6 features to throw in "normal mode"? 

For example, I'm writing node >= 0.10 code that doesn't pass thru babel at or during the time of use.
However, sometimes I accidentally throw in a `const` or something.

In that case, `esnext: false` won't catch it, since its option value is irrelevant (yes, clearly [forewarned here](https://github.com/sindresorhus/xo#esnext) too).

If this `esnext` behavior is to stay, then the option should be removed entirely.

Instead, I'd argue that it defaults to `true`, and affects the choice of `babel-eslint` vs normal `eslint` instead of a 100% override.

**Comment by sindresorhus** [comment]
The `esnext` mode is for enforcing ES2015+ features. XO should run on anything by default as that's the whole point of a *zero config* linter.

If you want errors when you use unsupported features, a better solution would be https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md It catches everything, not just syntax.

**Comment by lukeed** [comment]
Thanks, didn't know about that rule.

I still think that have `esnext` as an option is useless if XO's behavior is the same, regardless of a `true` or `false` value. I'm not saying that the behavior is wrong. 😄

**Comment by lukeed** [comment]
For anyone in the future who comes across this, here's [how I set up](https://github.com/lukeed/ExBox/commit/d73319810e95c1669f31757c73234965e9e30947) the `node/no-unsupported-features` rule.

**Comment by jamestalmage** [comment]
I can understand the confusion here. Maybe we could improve the docs.

**Comment by sindresorhus** [comment]
The behavior is not the same. When `esnext: true`, we apply these extra rules: https://github.com/sindresorhus/eslint-config-xo/blob/131724cbbd9c8ea680bf15f1cadd619253902820/esnext.js#L9-L33

**Comment by lukeed** [comment]
Ohh.. I see! Funny, I've never set `esnext` to `true` simply because it came enabled out of the box.

Then yea, at the very least, change "Enable ES2015+ rules." to something like:

```
Enforce ES2015+ rules. Using this flag will **prefer** ES2015+ syntax and conventions.

> **Note:** ES2015+ is parsed even without this option. You can already use ES2016 features like async/await and decorators. For a full list of features see Babel's experimental features and their Learn ES2015._
```

**Comment by sholladay** [comment]
My 2¢ here. I also think `esnext` should default to `true`.

I would break this down into three cases. Two out of three - and the ones I consider most common - require configuration when they should be _zero config_.

### New projects

`esnext` is clearly beneficial here. Rules like `prefer-const` and `prefer-arrow-callback` can teach you new things about the language and make a meaningful positive impact on a lot of code. If I'm making something new, it makes sense to take advantage of this.

### Old projects trying to freshen up

If I am applying XO to old projects, it's usually to modernize them. I have already resigned myself to the fact that there will be lots of drastic changes with noisy diffs. I very much want XO to make this codebase feel new again.

### Old projects with little time or stuck on IE

Given that XO is a strict and opinionated linter, I would be surprised if it would be easily applied to these projects without a lot of overrides. I think it makes sense to place the burden of configuration on this use case.

**Comment by sindresorhus** [comment]
@sholladay Yes, I've been planning to make `esnext: true` by default in the next version, in a couple of weeks.

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/xo/commit/61c046cab3d908c4c0582211d215e4c7f0d7cf20
