### ISSUE TITLE
Add support in syntastic

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/xo#112]
This is more of a to-do but it'd be great if we could get support for XO in [syntastic](/scrooloose/syntastic) as a checker. I know it'd be more suitable to have an issue over there, but it'd ultimately be one of us submitting the PR.

[This is where it'd need to go](https://github.com/scrooloose/syntastic/tree/master/syntax_checkers/javascript) (also, [hintety-hint](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/javascript/eslint.vim)).

Easily a beginner/moderate PR with a relatively good amount of potential street cred, especially since XO has a pretty straightforward configuration process.

**Comment by sindresorhus** [comment]
Already tried: https://github.com/scrooloose/syntastic/pull/1561

**Comment by Qix-** [comment]
Shucks, didn't see that.

I totally agree on the rationale, though. Glad they accommodated.
