### ISSUE TITLE
Replace eslint-plugin-import-order with eslint-plugin-import?

### ISSUE THREAD

**Issue by wenzowski** [sindresorhus/xo#114]
The current `import-order/import-order` rule is being provided by the deprecated [jfmengels/eslint-plugin-import-order](https://github.com/jfmengels/eslint-plugin-import-order).

That repository directs us to [benmosher/eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) which has the following [default import order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs%2Frules%2Forder.md)

```javascript
"import/order": ["error", {"groups": ["builtin", "external", "internal", "parent", "sibling", "index"]}]
```

It looks like these rules may be landing directly in eslint as well. See eslint/eslint#5583

**Comment by sindresorhus** [comment]
In the works: https://github.com/sindresorhus/xo/pull/109

There are some issues with the plugin that needs to be resolved first.
