### ISSUE TITLE
comma-dangle

### ISSUE THREAD

**Issue by ccorcos** [sindresorhus/xo#115]
http://eslint.org/docs/rules/comma-dangle

I'd like to add the following rule, but it doesnt work:

`comma-dangle: ["error", "only-multiline"]`

**Comment by sindresorhus** [comment]
How are you adding it? Can you share your XO config?

**Comment by ccorcos** [comment]
in my package.json:

```
  "xo": {
    "space": 2,
    "semicolon": false,
    "rules": {
      "no-new-func": 0,
      "guard-for-in": 0,
      "new-cap": 0,
      "no-use-before-define": 0,
      "camelcase": 0,
      "comma-dangle": ["error", "only-multiline"]
    }
  },
```

And its not complaining about the lack of a comma here, among other places...

```js
const defaultProto = (type) => {
  proto(type, {
    equals: (a, b) => a._name === b._name && all(k => equals(a[k], b[k]), type._fields),
    toString: (x) => `${type._name}(${type._fields.map((y) => x[y].toString()).join(', ')})`
  })
}
```

**Comment by sindresorhus** [comment]
Doesn't seem to work with ESLint either (which XO uses underneath).

```js
eslint file.js --env=es6 --rule='comma-dangle: [2, only-multiline]'
```

**Comment by ccorcos** [comment]
Hmm. Well that's too bad!

**Comment by sindresorhus** [comment]
I'd suggest you open an issue on ESLint about it.

**Comment by ccorcos** [comment]
https://github.com/eslint/eslint/issues/6198
