### ISSUE TITLE
Allowing more file extensions

### ISSUE THREAD

**Issue by t2t2** [sindresorhus/xo#117]
Currently file extensions are [limited to .js and .jsx](https://github.com/sindresorhus/xo/blob/master/index.js#L27), but that limits the use to those extensions even if the pattern is set to match some other extensions that eslint can lint (either standalone or with a plugin, for example `**/*.{js,vue}` with eslint-plugin-html)

**Comment by sindresorhus** [comment]
Yeah, agreed. It should only limit to .js/jsx if you don't specify a file extension in the glob.
