### ISSUE TITLE
colorized output truncated in node 6

### ISSUE THREAD

**Issue by wenzowski** [sindresorhus/xo#118]
Everything works beautifully with latest stable `xo` in node 5. Switching to node 6, output is truncated after a few lines. Piping output through a filter prevents clipping, for instance by doing `xo | tee`.

**Comment by sindresorhus** [comment]
Yes, this is a known Node.js 6 bug. It's going to be fixed very soon (https://github.com/nodejs/node/issues/6980#issuecomment-221713311).

**Comment by wenzowski** [comment]
Excellent! :)
