### ISSUE TITLE
Issue with new-cap rule with yeoman-test

### ISSUE THREAD

**Issue by sondr3** [sindresorhus/xo#119]
I'm currently using XO together with Yeoman and it's test libraries, however XO trips up on one of the asserts used by `yeoman-test` called `JSONFileContent` due to the `new-cap` rule.

```sh

  test/gulp.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  test/uploading/aws.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  test/uploading/rsync.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  3 errors
```

But there's nothing I can do about this other than override the global rule as far as I can tell because there's no way to ignore lines (which I think is a good thing). Thanks 😃

**Comment by sindresorhus** [comment]
I would open an issue on `yeoman-test` about fixing the method name. It's common convention in JavaScript that `new`'able things are PascalCase and variables camelCase.

You can easily override it with `// eslint-disable-line` or `/* eslint-disable new-cap */` at the top of the file.
