### ISSUE TITLE
Function with arguments in a spec file not parsed correctly?

### ISSUE THREAD

**Issue by plumlee** [sindresorhus/xo#120]
The code (using Mocha + Chai + expect):
```
    it('should convert the arguments of a function to an array', function () {
      var testFn = function (a, b, c) {
        return utils.toArray(arguments);
      };
      expect(testFn(1, 2, 3)).to.deep.equal([1, 2, 3]);
    });
```

Run as above outputs:
`error  'c' is defined but never used  no-unused-vars`

Remove the third argument:
```
    it('should convert the arguments of a function to an array', function () {
      var testFn = function (a, b) {
        return utils.toArray(arguments);
      };
      expect(testFn(1, 2)).to.deep.equal([1, 2]);
    });
```

Run as above outputs:
`error  ‘b' is defined but never used  no-unused-vars`

And then the same if you take it all the way down to just `a`.

Same happens if I try it as a named function versus a variable.

Config via package.json:
```
  "xo": {
    "envs": [
      "browser"
    ],
    "globals": [ "it", "describe", "beforeEach", "afterEach", "before", "after" ],
    "ignore": "src/lib/*.js",
    "rules": {
      "no-unused-expressions": 0
    },
    "space": true
  }
```

**Comment by sindresorhus** [comment]
Yes, that's how the `no-unused-vars` rule works. You never directly use any of the `a` `b` `c` arguments.

-

Also, instead of defining `globals`, do this instead:

```json
"envs": [
      "browser",
      "mocha"
]
```

**Comment by Qix-** [comment]
Hint: remove the arguments 💃 Javascript functions will take any arguments you pass them, but any arguments outside the various *named* arguments are only accessible in `arguments`. Therefore, change `function (a, b, c)` to just `function ()` and it'll work as expected and XO won't be throwing any errors.

**Comment by plumlee** [comment]
I wasn't clear in calling out the root issue - not that it's reporting the error, but that it's only finding the **last** argument and calling out that error, versus seeing three errors. Unless the eslinting process normally only returns the last error on any given line, it should throw an error for all three arguments that are declared but not used - `a`, `b`, and `c`.

If I include a statement such as `var a, b, c;` but never use those again, xo correctly reports errors for all three (as well as the expected `one-var` error). That's what I'd expect from the case above. Because it is always the last argument that causes the error, it feels that there is a parsing/tree error somewhere that's failing to properly iterate through all the passed arguments.

Does that seem reasonable or is this working as expected and I'm missing something else?

Thanks for the hint about the `mocha` environment.

@Qix- DOH, I should have thought of that. Once I wrote the initial `expect` line, I zeroed in on passing the three arguments. Thanks.

**Comment by sindresorhus** [comment]
@plumlee I agree. Probably an oversight. Can you open an issue about it on the [ESLint issue tracker](https://github.com/eslint/eslint/issues)? That's what's used underneath for the linting and where that rule belongs.

**Comment by plumlee** [comment]
A direct run of eslint at their most current version (2.11.1) against the same file gives no errors. So I suspect that it's already fixed, but will fork xo and test with that version and get back to you.

**Comment by Qix-** [comment]
@plumlee not sure if I'm wrong here but ESLint doesn't show any errors without being configured. Have you tried updating the version used by XO and testing against it?

**Comment by plumlee** [comment]
That's my test plan for tonight.

**Comment by plumlee** [comment]
@Qix- you were correct. Steps:

1. fork xo repo
2.edit package.json to require eslint 2.11.x
3. in that directory run `npm link`
4. jumped to my repo with the code above and ran `rm -rf node_modules/xo && rm -rf node_modules eslint*`
5. ran `npm link xo`
6. Ran the test and I still get the error.

Opened an issue on the eslint repo: https://github.com/eslint/eslint/issues/6316

**Comment by plumlee** [comment]
@Qix- See the link above for their response; this is expected behavior. It could be overridden in the xo configuration, but seems to me that might be getting into the weeds with eslint config. I have no issue with closing this now, even though it’s non-obvious if you don’t do a deep dive into the rules. My own preference would be to have it set to `all`, but that might start throwing a lot of errors people are not used to seeing.

**Comment by Qix-** [comment]
Ah makes sense. That's a call by @sindresorhus but that's a tricky situation.
