### ISSUE TITLE
how to disable "Missing space before function parentheses."

### ISSUE THREAD

**Issue by cheshire137** [sindresorhus/xo#121]
I didn't see anything in the README about this. How can I adjust my xo settings so that it does not complain "Missing space before function parentheses" when I have `function()` instead of `function ()`?

**Comment by jamestalmage** [comment]
You can override the `rules` section, as stated [here](https://github.com/sindresorhus/xo#rules).

Default rules [here](https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js).

ESLint docs on configuring rules [here](http://eslint.org/docs/rules/).

```json
{
  "xo": {
    "rules": {
       "rule-you-wish-to-disable": 0
    }
  }
}
```

The default reporter lists the rule name to the right of the message.

**Comment by Qix-** [comment]
Does this mean Github is using XO @cheshire137? :D

**Comment by cheshire137** [comment]
Haha nah, this was on a personal JavaScript project of mine!

**Comment by Qix-** [comment]
@cheshire137 fair enough :)
