### ISSUE TITLE
Add `--quiet` flag

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#125]
Same as ESLint, to only show errors and not warnings.

**Comment by beatfreaker** [comment]
For this do we have to change in config/opts that we send to `cliengine` to lint the files or we have to filter the results received from `eslint` ?

**Comment by sindresorhus** [comment]
See how it's done here: https://github.com/sindresorhus/grunt-eslint/blob/master/tasks/eslint.js#L41

**Comment by efegurkan** [comment]
Is thus issue still relevant? It looks like #131 closes it.
