### ISSUE TITLE
use "smart" eqeqeq

### ISSUE THREAD

**Issue by Haroenv** [sindresorhus/xo#132]
When using a `typeof something == 'undefined'` `xo` requires you to use `===`. When looking up this alert, I found that there exists an option called [smart](http://eslint.org/docs/rules/eqeqeq#smart ) that allows `==` when it's a better choice. Would it be a good idea to enable that by default?

**Comment by sindresorhus** [comment]
`==` is never a better choice. In this case both work, but `===` is better for consistency and clarity.
