### ISSUE TITLE
Can't change or turn off filename-case rule

### ISSUE THREAD

**Issue by seriema** [sindresorhus/xo#133]
I tried overriding `xo` rules in `package.json`.

`"filename-case": "camelCase"` gives:

```
Error: CLI:
	Configuration for rule "filename-case" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"camelCase"').
```

`"filename-case": 0` and `"filename-case": "off"` gives:

```
 ✖    4:1   Filename is not in kebab case. Rename it to fitbit-client.js.
```

**Comment by sindresorhus** [comment]
You have to use the exact rule name ESLint prints in the output. Since it's a plugin it needs to include the plugin name: `"xo/filename-case": "camelCase"`.

**Comment by jfmengels** [comment]
Actually, you'd need to set it this way: `"xo/filename-case": ["error", "camelCase"]`.

**Comment by maxleiko** [comment]
Actually, you need to specifically give the plugin in the list in order to override the rule, otherwise it won't work.  
The full example for overriding `unicorn/filename-case` is something like:

```json{
  "name": "your-awesome-package",
  "version": "42.0.0",
  "description": "Awesomeness",
  "main": "src/MyAwesomeThing.js",
  "dependencies": {},
  "devDependencies": {
    "xo": "^0.17.1"
  },
  "scripts": {
    "test": "xo && ava"
  },
  "xo": {
    "plugins": ["unicorn"],
    "rules": {
      "unicorn/filename-case": ["error", { "case": "pascalCase" }]
    }
  }
}
```
