### ISSUE TITLE
Upgrade to eslint v3?

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/xo#134]
Seems like it is not very API-breaking: http://eslint.org/docs/user-guide/migrating-to-3.0.0

**Comment by sindresorhus** [comment]
It requires Node.js 4, which *is* breaking. Nothing really interesting there yet, so I'll do it as soon as I have time.

**Comment by wmertens** [comment]
How about allowing both as a dependency, and if a project has 3.0 as an own dep, xo will use it automatically?

Hmm actually that would install v3 if you install xo, correct? Or would npm be smart enough to see that node 0.12 means installing v2?

**Comment by sholladay** [comment]
This can be closed.

See: https://github.com/sindresorhus/xo/commit/ac931aa32a06283dceb714deefe0968c4aba5435#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L68
