### ISSUE TITLE
filenames?

### ISSUE THREAD

**Issue by charlespeters** [sindresorhus/xo#135]
just started using xo yesterday and i ran into a rule i found confusing. i'm curious as to why filenames are being linted in xo; i'm not sure of the rationale behind doing that. so i'm wondering what difference it makes to have certain files named certain ways. can anyone clarify?

**Comment by jfmengels** [comment]
Unless there is a rule I'm not aware of, you are talking about [this rule](https://github.com/sindresorhus/eslint-plugin-xo/blob/master/docs/rules/filename-case.md).

Basically, like a lot of stylistic rules, it is to enforce a consistent naming convention in a project. If you go for `kebabCase` or `snakeCase`, it can avoid odd things with regards to filename cases on OSX (or so I heard, I don't have one).

**Comment by mrmartineau** [comment]
@jfmengels do you know how we can override the filename rule?

**Comment by sindresorhus** [comment]
@mrmartineau It's in the docs: https://github.com/sindresorhus/xo#rules

**Comment by mrmartineau** [comment]
@sindresorhus thanks, I did look at that but found differing ways to do it from other issues that folks have raised.
