### ISSUE TITLE
xo/catch-error-name: catch confounded with the method catch from promises

### ISSUE THREAD

**Issue by alcalyn** [sindresorhus/xo#137]
I get this lint error:

    The catch parameter should be named err.  xo/catch-error-name

The code that generated this error:

``` js
$http({
    method: 'get',
    url: '/api/path'
}).then(function (r) {
    // ...
}).catch(function (r) { // <- HERE
    // ...
});
```

The catch is not the try/catch one, but the promise one. So it expects I pass an `err` argument but found a callback.

The expected behaviour should be that it should not raise error from catch methods.

**Comment by jfmengels** [comment]
https://github.com/sindresorhus/eslint-plugin-xo/blob/master/docs/rules/catch-error-name.md

This rule is meant to enforce a consistent name for "error" variables, and it is meant to apply in bot try/catch and Promise.catch. This is expected behavior.

**Comment by alcalyn** [comment]
Ah ok thanks, didn't found that.
