### ISSUE TITLE
No way to pass `settings`?

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/xo#138]
The eslint-import checker is nice but it needs to be told about my webpack config. However, I don't see how to provide the `settings` key to eslint.

**Comment by sindresorhus** [comment]
Yeah, I didn't even know about the `settings` option until I added the `import` plugin. Should be supported here though. Pull request welcome as I don't have time right now to add it myself.

**Comment by wmertens** [comment]
I'll give it a shot, any quick pointers on where you think it should go?

Also, since I have your attention :), when I run XO from command line is
seems that a output will be cut off after 20 or so lines. Can't find why,
is that supposed to happen?
