### ISSUE TITLE
How can i pass a config file with npm command line ?

### ISSUE THREAD

**Issue by kevincaradant** [sindresorhus/xo#141]
Hi

I try to create a xo config in a file.js. 

I have to start it with xo and webpack. 

For webpack, i write this: 
```
xo: {
		configFile: './.eslintrc'
	},
```

This works well.

But this commands in my package json (script): 
`"xo": "xo ./.eslintrc",`
or this
`"xo": "xo .eslintrc",`

does not work :/. 

I get this
![image](https://cloud.githubusercontent.com/assets/6093175/18418110/8540c7a4-7840-11e6-84fd-521f2f9feb04.png)

Do you have an idea why ? 

Thank you

**Comment by kevva** [comment]
You can't supply a custom `.eslintrc`. Instead, [`extend`](https://github.com/sindresorhus/xo#extends) a shareable config or set your own rules using the [`rules`](https://github.com/sindresorhus/xo#rules) in your `package.json`.

**Comment by kevincaradant** [comment]
Oh oki thank you for this very fast answer but in this case, how can i use the same config between my webpack plugin xo and this xo library ? i'm a little bit lost about the possibilities :/

**Comment by kevva** [comment]
I don't think the webpack loader supports a config either.

**Comment by kevincaradant** [comment]
Yes that work a config file like i mention just before in my main post ;)
