### ISSUE TITLE
Not able to use xo --fix

### ISSUE THREAD

**Issue by akashnimare** [sindresorhus/xo#144]
So everything works expect --fix option. I'm not sure where I'm going wrong. Test file - 

``` javascript
var menubar = require('menubar')
var electron = require('electron');
var app = electron.app
var {Menu} = require('electron')

var mb = menubar({transparent: true, width: 340, height:600, icon: __dirname + '/img/Icon.png'})

var template = [
  {
    label: 'Foco',
    submenu: [
      {
        label: 'Reload',
        accelerator: 'CmdOrCtrl+R',
        click: function (item, focusedWindow) { if (focusedWindow) focusedWindow.reload() }
      },
      {
        label: 'Quit App',
        accelerator: 'Command+Q',
        selector: 'terminate:'
      },
      {
        label: 'Toggle DevTools',
        accelerator: 'Alt+Command+I',
        click: function () { mb.window.toggleDevTools() }
      }
    ]
  }
]

mb.on('ready', function ready () {
  var menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
})

```

Package.json 
``` json
  "scripts": {
    "test": "xo index.js --fix"
     },
    "xo": {
      "esnext": true,
      "semicolon": false,
      "envs": [
        "node",
        "browser"
      ]
    }

```
running npm run test  does not automagically fix anything (shows 60+ errors). XO is installed locally as well as globally. I was hoping someone could point me to right direction.

**Comment by kevva** [comment]
This is due to the limited support for autofixing in ESLint right now. See https://github.com/eslint/eslint/issues/5329. For example `var` isn't converted to `const` due to potential scope issues. Ultimately, this isn't something we can fix in XO.

**Comment by akashnimare** [comment]
@kevva thanks for explaining this. Does it auto fix indentation errors?

**Comment by kevva** [comment]
@akashnimare, currently, it does more bad than good if you're working with tabs https://github.com/eslint/eslint/issues/6702.

**Comment by akashnimare** [comment]
> it does more bad than good

@kevva Haha 😺 . My indentation level got fucked up after using this 😭 .
