### ISSUE TITLE
Clarification of config in `package.json`

### ISSUE THREAD

**Issue by dthree** [sindresorhus/xo#15]
I use spaces, so runnign `xo --space` works fine.

However, when trying to throw this into my `package.json`, this doesn't seem to accept args like ESLINT would:

```text
  "xo": {
    "envs": ["node", "mocha"],
    "rules": {
      "indent": [2, 2, {"SwitchCase": 1}],
    }
  }  
```
This isn't applying two-space indentation. 

Am I missing something?

**Comment by dthree** [comment]
NVM. Had a trailing comma in `package.json`, and so XO just up and ignored it.

It would be really cool if XO could catch that it isn't reading `package.json` due to malformed JSON and warn the user!

**Comment by markogresak** [comment]
I'd recommend you to install a JSON plugin in your editor, it should detect and highlight malformed JSON. If you're using atom, that should work by default.
Although adding an error message to notify the user of error in package.json wouldn't be very difficult.

**Comment by dthree** [comment]
I'll do that for sure. But adding the error would be the kind of one-up that makes packages like XO awesome.

**Comment by sindresorhus** [comment]
Sure. Btw, use the `space: true` option instead of `"rules": {"indent": [2, 2, {"SwitchCase": 1}]}`.

**Comment by dthree** [comment]
Thanks and will do :)
