### ISSUE TITLE
Ignored paths are not respected when linting files without extension

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/xo#156]
I am trying to upgrade a project to XO 0.17 (https://github.com/zeit/now/pull/79), and in version 0.16, it works fine. When bumping to 0.17, some folders that were previously ignored are now being linted.

I have overridden the `extensions` option to `["", ".js"]` in order to include (bin) files without extensions. At the same test, I have a ignored fixtures folder at `test/_fixtures/`, while I am linting `test/`.

What happens is that, at [this point](https://github.com/sindresorhus/xo/blob/master/index.js#L37-L41), the ignores is properly set and you get all the good files and directories. But, because I have overridden the extensions to allow `""`, directories are not filtered out. Then when those paths get passed to ESLint, it gets run on the `test/` folder, which causes all of its subdirectories, including `test/_fixtures` to be linted too.

I think that adding the `no-dir` option to `globby` would solve the problem, but I am pretty tired so I don't know if that solves it properly without creating new problems :sweat_smile:

**Comment by sindresorhus** [comment]
Yeah, setting `nodir` might be an ok temp solution, since we don't support `$ xo dir` currently anyways. The real solution however would be to do https://github.com/sindresorhus/globby/issues/33.

Wanna do a pull request?

**Comment by jfmengels** [comment]
Sounds good, putting it on my todo list.
