### ISSUE TITLE
Notify about incorrect config

### ISSUE THREAD

**Issue by markogresak** [sindresorhus/xo#16]
As mentioned in issue #15, there is no error handling when reading `package.json` ([index.js:40](https://github.com/sindresorhus/xo/blob/master/index.js#L40)), it's ignored and execution continues without user knowing what happened. 

It would be great to put a message to notify the user something bad happened and maybe even stop the execution. I'm not sure about the last one, but in my opinion, incorrect npm config isn't something one would even want.
I'm willing to work on it after we clarify what exactly should happen.

**Comment by sindresorhus** [comment]
Yup, I agree. Working on this right now.

**Comment by markogresak** [comment]
I saw your json parser on Changelog nightly, nice work :+1:

**Comment by sindresorhus** [comment]
The output is now a lot more helpful:

```
JSONError: Unexpected token ',' at 27:5 in package.json
  },,
```
