### ISSUE TITLE
No support for babel-preset

### ISSUE THREAD

**Issue by haskellcamargo** [sindresorhus/xo#161]
After updating to the last version of `xo`, several syntax errors are happening. I'm using _Babel_ with its presets, like support for _static properties_, but `xo` now is not able to parse them because the external _Babel_ support has been dropped. :broken_heart: 

```javascript
class Test {
  static cats = [] // Unexpected =
}
```

Well...
![image](https://cloud.githubusercontent.com/assets/7553006/20191390/69ca80e0-a76c-11e6-934a-264457fd2c6f.png)

**Comment by sindresorhus** [comment]
It's documented in the release notes: https://github.com/sindresorhus/xo/releases/tag/v0.17.0

I removed it as it was buggy and made linting slower, and I only had it to get support for async/await, which is now supported in ESLint.

**Comment by kevva** [comment]
> Adding a note somewhere in the README might be very useful to users.

https://github.com/xojs/xo#parser.
