### ISSUE TITLE
lintText does not apply ignores config

### ISSUE THREAD

**Issue by marionebl** [sindresorhus/xo#168]
`lintText` does not apply the [ignores](https://github.com/sindresorhus/xo#ignores) config as opposed to `lintFiles`. 

Given `lintText` has `opts.filename` and `opts.cwd` available we could compute if a given file should be ignored. 

Don't know if this is less intuitive, though. What do you think @sindresorhus?

---

* https://github.com/sindresorhus/atom-linter-xo/issues/22

**Comment by sindresorhus** [comment]
👍  We could use [`multimatch`](https://github.com/sindresorhus/multimatch), which supports the same patterns as `globby`, but works on paths instead of the actual filesystem.
