### ISSUE TITLE
Allow AVA helper filename convention

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/xo#172]
I currently get the following error running the test suite for `ava-files`.

```
  fixtr/default-patterns/test/_foo-help.js:1:9
  ✖    1:9  Filename is not in kebab case. Rename it to foo-help.js  xo/filename-case
```

Should we allow leading underscores? Should we only allow it in the default test and fixture folders?

Note: `ava-files` does not use the default fixture folder (so if we only allow it for the default folders, we would need to explicitly add an exception anyways).

Ref: https://github.com/avajs/ava-files/commit/3f2a63acae61fd7c86677a298618e3222650557e

**Comment by sindresorhus** [comment]
I think we should allow it anywhere. It's common convention in many ecosystems.

**Comment by sindresorhus** [comment]
Moved to https://github.com/sindresorhus/eslint-plugin-unicorn/issues/79.
