### ISSUE TITLE
Chain methods get wrong indent

### ISSUE THREAD

**Issue by warapitiya** [sindresorhus/xo#173]
When using **_--fix_** argument chain methods or promises get wrong indent. ESlint looks handling it perfectly. What causing this issue?

**Actual output:**

```js

	api
               .authenticate({})
               .then(function (result) {
	if (result.hasError) {
		console.error('Error');
	} else {
		console.log('Batman!');
	}
});
```

**Expected:**
```js
    api
        .authenticate({})
        .then(function (result) {
            if (result.hasError) {
                console.error('Error');
            } else {
                console.log('Batman!');
            }
        });
```

**_XO: 0.17.1_**

**Comment by sindresorhus** [comment]
Try reinstalling XO. The ESLint version used by XO might be outdated and that will ensure you have the latest.

**Comment by sindresorhus** [comment]
Alright. Closing. Report at https://github.com/eslint/eslint/issues (Make sure to check that there isn't already an issue for this).
