### ISSUE TITLE
question: add an eslint rule that isn't in the default xo set?

### ISSUE THREAD

**Issue by tony-kerz** [sindresorhus/xo#174]
love being liberated from managing eslint config!

some of the projects i work on use the [no-console](http://eslint.org/docs/rules/no-console) rule. 

is there a strategy to augment xo with an additional rule like that?

**Comment by Qix-** [comment]
It's [in the readme](https://github.com/sindresorhus/xo#rules), along with all of the other documentation about XO :)

**Comment by tony-kerz** [comment]
hi @qix,

sorry for being dense.

i had read over the read-me, and when i read [that section](https://github.com/sindresorhus/xo#rules) the language made me think it was about overriding settings on rules that were already in the xo rule set, but based on your comment, i made the leap that it just merges what is provided and lo-n-behold, the following works like a champ in `package.json`:

```
  "xo": {
    "space": true,
    "semicolon": false,
    "rules": {
      "no-console": "error"
    }
  }
```

thanks for the clue!
