### ISSUE TITLE
Support the `--stdin-filename` option in eslint

### ISSUE THREAD

**Issue by w0rp** [sindresorhus/xo#175]
For plugins like my plugin for running linters on Vim text buffers, it's useful to both pass text via stdin, but still specify what the filename for the text you are editing is. This can help some `eslint` plugins, etc.

Could you support the `--stdin-filename` option in `eslint`? The `xo` wrapper would have to somehow forward this option on to `eslint`. It is mentioned here: http://eslint.org/docs/user-guide/command-line-interface

**Comment by sindresorhus** [comment]
This is already supported with the `--filename` flag. I just forgot to document it. See: https://github.com/sindresorhus/SublimeLinter-contrib-xo/blob/ba4c6fdb6eb129720ebd83356aa3da55a46a1458/linter.py#L16

**Comment by sindresorhus** [comment]
Made it official as `--stdin-filename` for clarity and consistency with ESLint.
