### ISSUE TITLE
Ignoring files don't work

### ISSUE THREAD

**Issue by jcubic** [sindresorhus/xo#177]
I'm running this:
```
xo --space --global jQuery --ignore *min.js
```
Also try this:
```
xo --space --global jQuery --ignore "*min.js"
```
but it keep processing file `js/jquery.mousewheel-min.js`, how can I disable that file or any minified file?

I'm using GNU/Linux node 4.2.6.

**Comment by sindresorhus** [comment]
`--ignore "*min.js"` only matches files in the current directory. You want to match in a subdirectory, so should be `--ignore "**/*min.js"`. I would also rather do `--ignore "**/*-min.js"` to ensure you want match files like`jasmin.js`.

More about glob patterns: https://github.com/isaacs/node-glob#glob-primer

**Comment by sindresorhus** [comment]
If you intend to use this persistently in a project, I would recommend putting those options in the package.json config instead.

**Comment by Qix-** [comment]
Another thing to note: without the quotes, your shell will most likely try to expand the glob to nothing for you. If it's one file, that might actually work - but if the glob matches more, then XO is going to receive `--ignore`, `foomin.js`, `barmin.js`, etc., changing how XO reacts to parameters (and probably trying to lint `barmin.js` and beyond).
