### ISSUE TITLE
Missing badge in XO repos

### ISSUE THREAD

**Issue by pablopunk** [sindresorhus/xo#178]
It seems all repos using the XO badge are missing the image. It's weird cause the `.svg` link in the src seems to work fine.

<img width="562" alt="screen shot 2017-01-31 at 4 14 35 pm" src="https://cloud.githubusercontent.com/assets/4324982/22484668/8777c0b8-e7d0-11e6-949a-38273b29a603.png">

**Comment by Qix-** [comment]
It's working fine for me. Can you clear your cache/ try in another browser?

**Comment by pablopunk** [comment]
It's weird, I tried with 3 browsers, then make my roomate try it with his computer. All missing. But with my phone it does work (both under WiFi and cellular data). Also in the JS console I get this:

<img width="1296" alt="screen shot 2017-01-31 at 4 30 37 pm" src="https://cloud.githubusercontent.com/assets/4324982/22485190/a78415e4-e7d2-11e6-950b-62f6a35683a0.png">

**Comment by Qix-** [comment]
Im on mobile, give me a minute.

**Comment by Qix-** [comment]
It's still working fine for me on MacOS. Those errors appear unrelated.

<img width="959" alt="screen shot 2017-01-31 at 1 35 05 pm" src="https://cloud.githubusercontent.com/assets/885648/22485326/1fce7bc0-e7ba-11e6-871a-9dd727e8e2ce.png">

What browser/system are you using? Are you visiting github via `http://` or `https://`? Could you look at the *Network* tab in Chrome and see what the response is for that particular image?

**Comment by pablopunk** [comment]
I'm on MacOS also. The responses seem to be fine tho.

<img width="1680" alt="screen shot 2017-01-31 at 4 42 15 pm" src="https://cloud.githubusercontent.com/assets/4324982/22485631/5fdd9d1c-e7d4-11e6-8b4e-af6c44e30f5a.png">

<img width="1680" alt="screen shot 2017-01-31 at 4 41 57 pm" src="https://cloud.githubusercontent.com/assets/4324982/22485640/6ced268a-e7d4-11e6-81a4-0da7e39f1972.png">

**Comment by pablopunk** [comment]
If this is just my issue and nobody is getting this error we should close this, I'll figure it out.

**Comment by vadimdemedes** [comment]
Fine here too.

**Comment by pablopunk** [comment]
Ok, I'll close it, thanks for the help guys 😄👍

**Comment by Qix-** [comment]
Yeah I'm not sure what to tell you; it does seem very strange. Seems like a Github thing O.o

Sorry about that!
