### ISSUE TITLE
Make `radix` a warning

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/xo#18]
The rule `radix` requires that `parseInt` has the second parameter, a radix. It is [intended to disallow octal notation](https://github.com/eslint/eslint/blob/master/docs/rules/radix.md), but has the side effect of not allowing auto base-10/base-16 determination in the event the second parameter is absent.

Could we make it a warning?

**Comment by sindresorhus** [comment]
Can you show a practical usage example of `auto base-10/base-16 determination`? I've never seen that.

The check is an error for a good reason. You really want predictability when parsing numbers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

> If the input string begins with "0", radix is eight (octal) or 10 (decimal).  Exactly which radix is chosen is implementation-dependent.  ECMAScript 5 specifies that 10 (decimal) is used, but not all browsers support this yet.  For this reason always specify a radix when using parseInt.

Ugh.

-

Seems like you can pass `0` to make it auto. Would `parseInt(foo, 0);` be acceptable?

**Comment by Qix-** [comment]
Yes, it would. I wasn't aware of the `0` radix. :+1:

The octal thing is understandably annoying and undesirable, which is why I suggested a warning instead of turning it off completely. Predictability is good, yes, but in the case of hex vs dec sometimes it's useful to not discriminate. Octals, however, should have no place anymore, unless explicitly specified with `parseInt(n, 8)`. Definitely agreed there.

Thanks!

**Comment by sindresorhus** [comment]
> The octal thing is understandably annoying and undesirable, which is why I suggested a warning instead of turning it off completely.

Making something a warning pretty much removes the biggest use-case of XO; failing a PR that doesn't lint. Unfortunately, very few contributors look at the output, and failing the PR is a good way to force them to fix stuff.

-

> but in the case of hex vs dec sometimes it's useful to not discriminate.

Do you have some code I can look at? I'm still curious about how it's used.

**Comment by Qix-** [comment]
> Unfortunately, very few contributors look at the output, and failing the PR is a good way to force them to fix stuff.

Truth, can't argue with that.

> Do you have some code I can look at? I'm still curious about how it's used.

Not off the top of my head; I have some C code somewhere that does something similar, though. One of the basic C functions can determine the format of the string just like `parseInt` does. It's useful for configuration files, for instance. Sometimes, I want a number for some configuration value but it only really makes sense as a hex number - however, because of certain tools, it might be easier to copy and paste the decimal version of it.

One instance I had was generating lldb commands for hot-writing pieces of memory - the generation step happening using Node. I passed in addresses and it spit out commands, but it had to use the numbers to do so. I could either pass it `0xAABBCCDD`, which made sense in most contexts, or I could pass it the decimal value from a list of register values all displaying decimal values (because the utility that displayed the register values doesn't recognize register values as addresses, hence displaying them as decimal).

The flexibility there made it so that I didn't have to convert from hex to dec or vice versa.

But I definitely never used octal ;)
