### ISSUE TITLE
xo and decorators?

### ISSUE THREAD

**Issue by tony-kerz** [sindresorhus/xo#180]
just getting into xo in combination with a react project.

is there a way to get xo to be ok with decorators?

decorators are mentioned briefly [here](https://github.com/sindresorhus/xo/commit/04733f1724a74c494458754d4982de53cdc30eeb#diff-0730bb7c2e8f9ea2438b52e419dd86c9L143), but this verbiage was removed. 

are they supposed to be supported and i'm just misconfigured, or are they shunned?

<img width="474" alt="screen shot 2017-02-04 at 3 24 13 pm" src="https://cloud.githubusercontent.com/assets/1223231/22621288/3ee79262-eaee-11e6-840f-ae6e8004681c.png">

**Comment by Qix-** [comment]
You can try adding `babel-eslint` to your `devDependencies` and in your package.json file add the following:

```json
{
    "xo": {
        "parser": "babel-eslint"
    }
}
```

Check the docs [here](https://github.com/sindresorhus/xo/blob/0d88cde7e860d55347c40363f8b8985d67b79026/readme.md#parser).

**Comment by tony-kerz** [comment]
thanks josh, works great! 👍

**Comment by Qix-** [comment]
Glad to hear it :)
