### ISSUE TITLE
Is there a way to disable camelcase within function params?

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/xo#185]
I currently can't change the backend to allow the params to use camelcase and I'd rather not disable the warning about camelcase for everything.

Is there a way to disable the check just for the `allowed_qualities` and `preferred_qualities`?

```
$.get('config/general/saveAddShowDefaults', {
    allowed_qualities: anyQualArray.join(','),
    preferred_qualities: bestQualArray.join(',')
});
```

**Comment by Qix-** [comment]
According to [the official ESLint documentation for the camelcase rule](http://eslint.org/docs/rules/camelcase), no.

However, you can [add per-line ESLint ignore directives](http://stackoverflow.com/questions/27732209/turning-off-eslint-rule-for-a-specific-line) to your code.

**Comment by OmgImAlexis** [comment]
I was hoping this project had possibly added something to work around that. 

Guess I'll have to stick with ignore lines.

**Comment by Qix-** [comment]
Ignore lines can be a good thing anyway; they clarify the intent of the code. :)

Feel free to close unless there is something else.

**Comment by sindresorhus** [comment]
You can also turn off the rule globally or per file. See the `rules` option. Though I would recommend preferin inline ignore comments.

**Comment by OmgImAlexis** [comment]
@sindresorhus that main reason I didn't want to use inline ignores is we use ajax and get requests quite a bit meaning most files contain 10 - 20 ignore lines just for those. If we could disable it just for certain functions like `$.get` that'd be a lot easier.
