### ISSUE TITLE
Change npm suggestion to yarn if yarn.lock is detected

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/xo#187]
I'm not sure if this library is what sets the description for the rule or if it's the linter itself but in atom I'm getting this error message when a dep isn't installed. I'd be nice if instead of recommending npm it shows `yarn add walk-promise -S` if a yarn.lock was found.

```
'walk-promise' should be listed in the project's dependencies. Run 'npm i -S walk-promise' to add it (import/no-extraneous-dependencies)
```

**Comment by jfmengels** [comment]
@OmgImAlexis The error comes from a rule in [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/). You should open an issue over there instead (please check if there isn't already one).

**Comment by sindresorhus** [comment]
Already declined: https://github.com/benmosher/eslint-plugin-import/issues/716
