### ISSUE TITLE
envs option doesn't work from within overrides option

### ISSUE THREAD

**Issue by davidpauljunior** [sindresorhus/xo#189]
It seems that errors are still flagged when specifying `envs` options within the `overrides` option.

For example, with the below configuration inside package.json, I still see `document is not defined` and  `window is not defined`.  Our xo version is specified as `"xo": "^0.17.0"`.

```
"xo": {
    "envs": [
        "node"
    ],
    "overrides": [
        {
            "files": "app/js/**/*.js",
            "envs": [
                "browser"
            ]
        }
    ]
}
```

**Comment by davidpauljunior** [comment]
Actually this seems to be the case for any overrides, not just `envs`.

**Comment by sindresorhus** [comment]
How are you using XO? Directly or through an editor plugin?

**Comment by davidpauljunior** [comment]
Directly through cli, e.g. `xo index.js`.

I've created a simple example if it helps? https://github.com/davidpauljunior/xo-overrides-test

**Comment by lsdriscoll** [comment]
@davidpauljunior I have this working for me without an issue. Here's my config:

```json
{
 "xo": {
    "space": true,
    "semicolon": false,
    "overrides": [
      {
        "files": "client/**/*.js",
        "envs": ["browser"]
      }
    ]
  }
}
```

node is applied as a default env so you shouldn't need to specify that at the top-level. Also try specifying the value as an array. Hope it works for you.

**Comment by davidpauljunior** [comment]
Looks like you're right @lsdriscoll, in my example repo I'd missed the enclosing array.  I'm sure I had these errors even with those, but as it's working now in my example repo, I'll close this.  Thanks for the comment.
