### ISSUE TITLE
Add ability to disable plugins?

### ISSUE THREAD

**Issue by CrashyBang** [sindresorhus/xo#191]
As far as I can tell the only way to currently disable plugins is via the eslint-disable comments i.e:

```js
/* eslint-disable import/no-unassigned-import */
```

I was wondering if it would be possible to add support for something like [this](
https://www.npmjs.com/package/eslint-plugin-disable) that would allow users to blanket disable a plugin from there `xo` config in the `package.json` (this would take some work), something like:

```json
"xo": {
  "eslint-plugin-disable": {
      "paths": {
        "import/no-unassigned-import": ["path/to/js/**/*.js"]
      }
    }
}
```

or

```json
"xo": {
  "eslint-plugin-disable": [
      "import/no-unassigned-import"
    ]
}
```

I am hoping to hacking together a PR but wanted your input before I started.

Cheers.

**Comment by sindresorhus** [comment]
You can use the config overrides targeted at a sub-path with the `rules` option.

**Comment by CrashyBang** [comment]
Hey @sindresorhus,

Sorry could you give an example of what that would look like?

Cheers,
Otis.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/xo#config-overrides

**Comment by CrashyBang** [comment]
Awesome got it :).

Thank you!
