### ISSUE TITLE
Recursive glob patterns

### ISSUE THREAD

**Issue by CrashyBang** [sindresorhus/xo#201]
Running `0.18.1` on Ubuntu 16.10 with Node `v7.7.1`.

I have the following command: `xo resources/**/*.js`.

I am trying to use it on the following structure:

```
├── admin
│   ├── assets
│       ├── main.js
└── webpack
    ├── config.js
```

Now that reports all linting failues in `config.js` but not `main.js` if I change that command to: `xo resources/**/**/*.js`. it now works but obviously I don't want to have to add a `/**` everytime I go one directory deeper.

I have looked at [globby#24](https://github.com/sindresorhus/globby/pull/24) and [cpy#10](https://github.com/sindresorhus/cpy/issues/10) but neither seemed to really address the issue.

Is this by intentition or is this a bug?

In an ideal world `xo resources/**/*.js` would traverse all folders underneath `resources` recursively.

Cheers.

**Comment by Qix-** [comment]
What happens when you use `xo 'resources/**/*.js'` (in single quotes)?

**Comment by CrashyBang** [comment]
Hey @Qix- that seems to have fixed it.

I am running as an npm script: `"lint:scripts": "xo 'resources/**/*.js'",`.

Cheers.

**Comment by Qix-** [comment]
Yep - without the single quotes, it's your shell trying to expand the double star, not XO. To get it to work otherwise, you'd need `shopt -s globstar` in your `.bash_profile`. But the single quotes is a better solution since it works for everyone. :)
