### ISSUE TITLE
Shield is broken! ☹️

### ISSUE THREAD

**Issue by SupremeTechnopriest** [sindresorhus/xo#208]
[![XO code style](https://img.shields.io/badge/code_style-XO-5ed9c7.svg)](https://github.com/sindresorhus/xo)

**Comment by Qix-** [comment]
Looks fine to me. What browser/operating system/version are you using? Are you behind a proxy?

**Comment by SupremeTechnopriest** [comment]
No proxy. I'm on `OSX 10.11.6` and `chrome 57`.  Looking in the network tab, it looks like the `xhr` is returning 200, but the response is empty.

![screen shot 2017-04-11 at 3 03 12 pm](https://cloud.githubusercontent.com/assets/2261598/24925971/04a861a4-1ec8-11e7-9789-250266dd0ad8.png)

![screen shot 2017-04-11 at 3 03 43 pm](https://cloud.githubusercontent.com/assets/2261598/24925986/14f3ce04-1ec8-11e7-86d9-da404af41503.png)

**Comment by SupremeTechnopriest** [comment]
This is how it is rendering on my screen.

<img width="862" alt="screen shot 2017-04-11 at 3 06 29 pm" src="https://cloud.githubusercontent.com/assets/2261598/24926107/7860db80-1ec8-11e7-9135-75a4416d165f.png">

**Comment by Qix-** [comment]
This is almost definitely a Github caching issue. I don't know why Github still insists on using their `githubusercontent.com` domain since it's only caused problems in the past.

See also: http://shouldiblamecaching.com/
