### ISSUE TITLE
xo still using import/no-amd with AMD env 

### ISSUE THREAD

**Issue by rijkvanzanten** [sindresorhus/xo#209]
Linting with `xo --env=amd` or config
```
"xo": {
  "envs": ["amd"]
}
```
still throws errors due to the `import/no-amd` (Expected imports instead of AMD define()) rule. Is this a `xo` specific error or should I report this issue at the `eslint` repo?

**Comment by sindresorhus** [comment]
Environments are different from rules and they don't affect each other. You need to disable the rule too.

**Comment by rijkvanzanten** [comment]
Ah thanks. Wasn't aware of that.
