### ISSUE TITLE
XO config in package.json is ignored when eslintConfig is also present

### ISSUE THREAD

**Issue by lucianlature** [sindresorhus/xo#21]
The problem I have is quite simple: my `package.json` contains a XO configuration, but when `eslintConfig` is also added to `package.json`, the last one take precedence over XO.

```
{
    "name": "my-awesome-project",
    "eslintConfig": {
        "extends": ["xo", "xo-react"]
    },
    "xo": {
        "esnext": true
    }
}
```

This configuration will load the XO defaults options, but the `esnext` option will be ignored. In order to fix this, https://github.com/sindresorhus/xo/blob/master/index.js#L66 needs to allow the `extends` option to also include the `eslintConfig`.

Or, even better, I want to be able to specify the `extends` option straight into XO, like this:

```
{
    "name": "my-awesome-project",
    "xo": {
        "esnext": true,
        "extends": ["xo-react"]
    }
}
```
which is equivalent of
```
{
    "name": "my-awesome-project",
    "xo": {
        "extends": ["esnext", "xo-react"]
    }
}
```

**Comment by ayhankuru** [comment]
same problem :(

**Comment by sindresorhus** [comment]
XO has an `extends` option now ;)
