### ISSUE TITLE
Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/xo#210]
While using xo in atom I added `!test/helpers/.setup.js` to my ignores array in `package.json` and all I get is this error. The weirdest bit if the error still happens even if the file is empty.

```
linter-registry.js [sm]:125 [Linter] Error running XO TypeError: Cannot read property 'messages' of undefined
    at /Users/xo/.atom/packages/linter-xo/lib/format.js:17:19
```

xo works fine when using it in the cli though; `xo test/helpers/.setup.js --ignore-pattern '!test/helpers/.setup.js'`.

**Comment by sindresorhus** [comment]
Can you open this on https://github.com/sindresorhus/atom-linter-xo instead if it's still an issue with the latest version of `linter-xo`.
