### ISSUE TITLE
Can not find included plugin `unicorn/*`.

### ISSUE THREAD

**Issue by ApricumMedia** [sindresorhus/xo#214]
Using `linter-xo@0.22.0` with the Atom Beta, the XO linter can not seem to find its own integrated version of `eslin-plugin-unicorn`. It outputs a variety of errors in the very first line of the code.

<img width="833" alt="screen shot 2017-04-26 at 23 44 47" src="https://cloud.githubusercontent.com/assets/7656669/25458701/3e98bf48-2adb-11e7-813f-1d06b6e6c1e0.png">

I already reinstalled the `linter` package, as well as `xo` with apm more than once.

**Comment by rockymadden** [comment]
With Atom releasing `1.17.0`, this is no longer just in Atom Beta.

**Comment by sindresorhus** [comment]
Should be fixed now. See: https://github.com/sindresorhus/atom-linter-xo/issues/74#issuecomment-309195313
