### ISSUE TITLE
Flow + XO Parsing error: Unexpected token : 

### ISSUE THREAD

**Issue by rohmanhm** [sindresorhus/xo#215]
I'm get trouble when using XO with Flow.

```javascript
function abc (a: string, b: string): string {
  return a + b
}
```
Throw error
> message: 'Parsing error: Unexpected token :'

You may consider add some documentation to integrate Flow with XO

**Comment by rohmanhm** [comment]
Fixed.
I missed add `babel-eslint` into my parser

**Comment by sindresorhus** [comment]
There already is documentation. I can't document every possible use-case. You need to use a different parser, like `Babel`.
