### ISSUE TITLE
`--open` should open the first error, not warning

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#219]
I have warnings in many projects and it's annoying that it opens at the warning instead of the error. If there are no errors, it should go to the first warning. I think we could just sort the errors first.

Should not be done until https://github.com/sindresorhus/xo/pull/218 is merged.

**Comment by tdeschryver** [comment]
if its OK, I would like to try implementing this.

**Comment by sindresorhus** [comment]
Go ahead :)

**Comment by Qix-** [comment]
Welcome to Github, @tdeschryver! :)

**Comment by tdeschryver** [comment]
@sindresorhus Just to be sure, it should only open the warnings if there are no errors?
@Qix- thanks! :)

**Comment by kevva** [comment]
> If there are no errors, it should go to the first warning

I take that as a yes @tdeschryver :).
