### ISSUE TITLE
Multiple config files for subdirectories

### ISSUE THREAD

**Issue by stefan-kern** [sindresorhus/xo#22]
i have a js/ folder where i want to lint with

"esnext": true,
"envs": [
  "browser"
]

and then i have my gulpfile folder where i want to lint with 

"esnext": false,
"envs": []

this works with .jshint files because i can have multiple of them in the different folders. but with xo the configuration is stored in the package.json which i tried duplicating with different rules into the different folders but it didn't work.

so i'm wondering if theres a solution already? seems like a common case.

**Comment by agirorn** [comment]
Could xo support .xorc or .eslintrc in sub-directories.

**Comment by sindresorhus** [comment]
You can put a package.json file there with just the XO stuff:

```json
{
	"xo": {
		"esnext": true,
		"envs": [
			"browser"
		]
	}
}
```

**Comment by jamestalmage** [comment]
> You can put a package.json file there with just the XO stuff

That did not work for me.

I am trying to add just `sinon` and `assert` as globals for tests, I put this in `tests/package.json`.

```json
{
  "xo": {
    "global": [
      "assert",
      "sinon"
    ]
  }
}
```

The package.json from the projects base folder has: 

```json
  "xo": {
    "envs": [
      "node",
      "mocha"
    ]
  }
```

**Comment by sindresorhus** [comment]
Oh, duuh, my mistake. Not sure what I was thinking... Not yet possible.

I haven't yet decided whether to do nested configs or have the top-level config be able to do file/glob specific options overrides. I'm quite busy right now, so I could use some help on this.

**Comment by jamestalmage** [comment]
I was thinking the "file/glob" specific overrides, just to start the conversation on what it might look like:

For boolean flags (`esnext`, `semicolons`, and  `space`), just replace with a glob string.

```js
"esnext": "**/test/*"
```

For arrays of strings (`envs`, `globals` - maybe `plugins`?) turn it into an object hash,

```js
"envs": {
  "node": true,
  "mocha": "**/test/*"
}
```

**Comment by sindresorhus** [comment]
See related ESLint discussion: https://github.com/eslint/eslint/issues/3611

**Comment by sindresorhus** [comment]
I was thinking something more like:

```json
{
	"xo": {
		"ignores": [
			"foo.js"
		],
		"overrides": {
			"test/**": {
				"esnext": true,
				"env": [
					"node",
					"browser"
				]
			}
	}
}
```

Alternatively this if we want to support multiple patterns:

```json
{
	"xo": {
		"ignores": [
			"foo.js"
		],
		"overrides": [{
			"files": ["test/**"],
			"esnext": true,
			"env": [
				"node",
				"browser"
			]
		}]
	}
}
```

Thoughts?

I'm not happy about the `overrides` name.
