### ISSUE TITLE
Marks parts of an empty arrow function as a syntax error

### ISSUE THREAD

**Issue by Nokel81** [sindresorhus/xo#224]
`() => {};`

Will sometimes produce `Parsing error: Unexpected token )` or `Parsing error: Unexpected token =>`

**Comment by schnittstabil** [comment]
Sorry, we cannot reproduce an error which occurs "sometimes". We need a little more information; for example a code snippet containing `() => {};` somewhere.

Just for the record: Linting a file, which contains only `() => {};` works as expected.
