### ISSUE TITLE
Allow custom errors to set name from constructor's name

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/xo#226]
The following code

```javascript
class ProtocolError extends Error {
	constructor(message) {
		super(message);
		this.name = this.constructor.name;
	}
}
```

yields the following error:

```
✖  16:15  The name property should be set to ProtocolError.  unicorn/custom-error-definition
```

The error isn't wrong in suggesting the name should be properly set, but it appears to only be looking for a literal.

It should also check for and allow the _exact_ path `this.constructor.name`.

**Comment by sindresorhus** [comment]
It's intentionally disallowing that, as it won't work when minified, since `this.constructor.name` might be a single character.

**Comment by Qix-** [comment]
ugh. okay. :|
