### ISSUE TITLE
inline configuration not working for exported variables

### ISSUE THREAD

**Issue by stefan-kern** [sindresorhus/xo#23]
In jshint and eslint you can configure exported variables with inline comments. in the XO linter the exported configuration that is described here: http://eslint.org/docs/rules/no-unused-vars.html doesnt seem to work. the /* globals */ configuration works fine however so it doesnt seem to be an issue of inline configurations in general.

/* exported Model */
var Model = 13;

linting it from the terminal with xo file.js thorws the error:
3:5  error  "Model" is defined but never used         no-unused-vars

i tried to lint the same file with the current eslint linter. that one worked fine. it threw an error without the /* exported Model */, and worked when i plugged it back in.

**Comment by sindresorhus** [comment]
Per https://github.com/eslint/eslint/commit/6c04d518c6c64bcd6b79f1ea482dd6cc45598bd4, this has no effect when the `env` is `node`/`commonjs` and when `modules: true`, of which, both are the case in XO. You can override this yourself, though.

**Comment by tcarlsen** [comment]
I know this issue is closed, but I can't seem to override `sourceType` to `script` I tried with `parserOptions` inside the `xo` property in `package.json` and in the `eslintConfig`. But nothing seems to work?

```json
"xo": {
    "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "script"
    },
    "esnext": true,
    "envs": [
      "browser",
      "es6"
    ],
    "space": 2
  }
```

**Comment by sindresorhus** [comment]
@tcarlsen Probably related: https://github.com/babel/babel-eslint/commit/991ec90290d4c62ab5bfdddada4aa9bbac625bd3
