### ISSUE TITLE
Parsing Error with dynamic imports

### ISSUE THREAD

**Issue by epiqueras** [sindresorhus/xo#232]
I have:

```json
// xo
"esnext": true,
```

and I still get a parsing error with `import(....`

Adding the parser explicitly in xo config (`"parser": "babel-eslint"`) doesn't help either.

**Comment by sindresorhus** [comment]
I'm not sure `import()` is even supported by Babel yet. It's a very new feature. Not really relevant here. You have to make sure the parser supports it.

**Comment by epiqueras** [comment]
esnext: true sets the parser to babel-eslint right?

I'm pretty sure babel-eslint supports import()

**Comment by kevva** [comment]
`esnext: true` only adds the rules in https://github.com/sindresorhus/eslint-config-xo/blob/master/esnext.js. Setting the parser to `babel-eslint` should work though since `babel-eslint` supports dynamic imports.

**Comment by epiqueras** [comment]
@kevva I set the parser and it still fails

**Comment by kevva** [comment]
And you have installed it I presume?

**Comment by epiqueras** [comment]
@kevva yes.

**Comment by kevva** [comment]
Works fine for me:

```js
// x.js
'use strict';
import('y.js').then(m => {
    console.log(m);
});
```

```json
// package.json
{
  "dependencies": {
    "babel-eslint": "^7.2.3",
    "xo": "^0.18.2"
  },
  "xo": {
    "parser": "babel-eslint"
  }
}
```

**Comment by epiqueras** [comment]
Oops,

The babel-eslint readme showed `babel-eslint@6` as the install. Upgraded to the newest version and it works fine now. Thanks!
