### ISSUE TITLE
Move the gitignore handling code to `globby`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#236]
As an optional feature in `globby`. It was a really difficult thing to implement, so would be nice if everyone could take advantage of and help improve it.

@marionebl @schnittstabil Thoughts?

**Comment by schnittstabil** [comment]
As far as I know `node-glob` does not support advanced _ignore patterns_ (like functions  for examples, see https://github.com/isaacs/node-glob/issues/261), hence we would only move the problem to `globby`–without any advantage, at least with the current [`getGitIgnoreFilter`](https://github.com/sindresorhus/xo/blob/0c6dbf50f5e23dc3f7a87b3a52d957dcf5d9ca2a/lib/gitignore.js#L26) approach.

**Comment by marionebl** [comment]
This does not solve any technical issues per se as @schnittstabil mentions but I think globby is the better package to host that concern. :+1:. I'll draft a PR for globby.

**Comment by sindresorhus** [comment]
@schnittstabil The advantage is that more projects would benefit from the code and help improve it. I need it for multiple other projects that are already using `globby`.

**Comment by marionebl** [comment]
@sindresorhus Which other projects are you planning to use this in?

**Comment by sindresorhus** [comment]
@marionebl AVA

**Comment by schnittstabil** [comment]
That sounds reasonable :+1:

**Comment by marionebl** [comment]
@sindresorhus I had more than one look at this and frankly am quite lost on how to do this in a way to improve on the current performance in a meaningful way. Perhaps you have an idea?

**Comment by sindresorhus** [comment]
@marionebl It's not about directly improving the performance, but rather moving it to a place where more projects can take advantage of the code, which makes it more likely to see performance fixes.

**Comment by sindresorhus** [comment]
@marionebl https://github.com/sindresorhus/xo/issues/235 is about improving performance.

**Comment by marionebl** [comment]
Ok, get it.

**Comment by sindresorhus** [comment]
It's now included in the Globby, so the next step would be to take advantage of it here: https://github.com/sindresorhus/globby/releases/tag/v7.0.0

**Comment by marionebl** [comment]
Had a brief look at this. We might want to expose `getGitIgnoreFilter` from `globby` to deal with the lintText use case in `xo`: 

https://github.com/sindresorhus/xo/blob/4273f8aa24b4c4dc2383d64e53d496f2e020481f/index.js#L65

**Comment by sindresorhus** [comment]
👍 Good idea
