### ISSUE TITLE
Document Reporters `--reporter` 

### ISSUE THREAD

**Issue by F1LT3R** [sindresorhus/xo#239]
I would like to change the XO output so that I can list the filename and number for each error, so that I am able to click a link for each error from the CLI. My first thought is to read the documentation and see if there is a reporter that already does this for me.

But I am unable to find documentation on how to use the `--reporter`.

- Can I change my reporter in my `xo` config in my `package.json`?
- What reporters can I used _out-of-the-box_?

**Comment by kevva** [comment]
> Can I change my reporter in my `xo` config in my `package.json`?

No. Just using the `--reporter` flag.

> What reporters can I used _out-of-the-box_?

All reporters that is supported by ESLint. There are some built in ones you can use out of the box http://eslint.org/docs/user-guide/formatters/.
