### ISSUE TITLE
Fix max-statements-per-line automatically

### ISSUE THREAD

**Issue by bokub** [sindresorhus/xo#242]
Consider the following line:

```js
const i = 0; console.log(i);
```

When running `xo --fix`, the `max-statements-per-line` error is not fixed.

At first sight, it doesn't seem too hard to do. Do you think it could be possible ?

**Comment by sindresorhus** [comment]
From the readme:

> Uses ESLint underneath, so issues regarding rules should be opened over there.

Try searching the ESLint issue tracker before opening an issue there. I'm sure it has been requested before.
