### ISSUE TITLE
Why eslint complaining about `const` is a reserved keyword?

### ISSUE THREAD

**Issue by zer09** [sindresorhus/xo#248]
Hello good day,

I initial a project using the ```generator-electron```, but on the index.js the ```const electron = require('electron')``` on line 2, eslint complaining about ```Parsing error: The keyword 'const' is reserved.````.

How I can fix it? as far as I know xo is managing the eslint config.

Thanks.

**Comment by emoticon** [comment]
Can you post your package.json / .eslintrc to [Hastebin](http://hastebin.com) or something similiar?

**Comment by zer09** [comment]
Hello thanks, this is my package.json [https://hastebin.com/tifuhokufa.json](https://hastebin.com/tifuhokufa.json)

**Comment by kevva** [comment]
Could you try upgrading `xo`? Also, are you running `xo` from the command line or is your editor that complains?

**Comment by zer09** [comment]
I am not using xo on command line, the linting error is from vscode.

I tried to upgrade xo to v0.18.2, but now eslint is asking for eslintrc file.
I am now getting this
```
[Info  - 9:35:52 AM] ESLint server is running.
[Info  - 9:35:53 AM] ESLint library loaded from: /home/.../node/hims-e/node_modules/eslint/lib/api.js
[Warn  - 9:35:53 AM] 
No ESLint configuration (e.g .eslintrc) found for file: index.js
File will not be validated. Consider running the 'Create .eslintrc.json file' command.
Alternatively you can disable ESLint for this workspace by executing the 'Disable ESLint for this workspace' command.
```

Thanks

**Comment by zer09** [comment]
I also tried ```0.17.0``` but the same result on ```0.18.2```, it is looking for ```eslintrc```.

**Comment by kevva** [comment]
Are you using the `xo` extension in VS Code? It will always look for a ESLint config file if you have ESLint installed, but you can ignore it. `xo` will work regardless if you have it in your `devDependencies`.

**Comment by zer09** [comment]
hmm sorry, but it didn't worked. Actually I don't have ```xo``` installed on vs, but I tried to install it. Then when I use it, it didn't worked. So I go back again on ```xo 0.16```.

**Comment by kevva** [comment]
This should work:

1. Install [`linter-xo`](https://github.com/SamVerschueren/vscode-linter-xo)
2. Add `"xo.enable": true` to your VS Code settings
3. `npm install --save-dev xo` in your project folder

Anyway, this sounds like a problem with your setup so I'm going to close this.
