### ISSUE TITLE
xo constantly transforms arrow functions

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/xo#249]
working on a legacy project using `xo --fix` with the following `package.json` configuration, it always transforms this `$(function() {` to `$(() => {` and ends with an error the next time `xo` is run (e.g. `Parsing error: Unexpected token )`)

```json
  "xo": {
    "extends": "prettier",
    "plugins": ["prettier"],
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "singleQuote": true,
          "bracketSpacing": true,
          "trailingComma": "none"
        }
      ]
    },
    "envs": ["node"],
    "space": true,
    "overrides": [
      {
        "parserOptions": {
          "ecmaVersion": 5,
          "sourceType": "script"
        },
        "plugins": ["compat"],
        "files": "assets/public/js/**/*.js",
        "envs": ["browser", "jquery"],
        "rules": {
          "compat/compat": "error"
        }
      }
    ]
  }
```

I also tried putting inside the browser rules `"prefer-arrow-callback": "off"` but that still didn't work.

**Comment by sindresorhus** [comment]
Either set the `esnext` option to `false` or disable the specific rule.

> I also tried putting inside the browser rules "prefer-arrow-callback": "off" but that still didn't work.

That should have done it. Can you share how it looks when you've included `"prefer-arrow-callback": "off"`.

**Comment by niftylettuce** [comment]
Interesting @sindresorhus, this only happens with <https://github.com/Chiel92/vim-autoformat>.

It's calling `xo` no different than I am either from command line <https://github.com/Chiel92/vim-autoformat/blob/2ecb5555dbec2737ac903222746669ca354afc04/plugin/defaults.vim#L170>.

**Comment by niftylettuce** [comment]
Perhaps it is because it is not respecting the file path given while naming the tmp file via overrides, a-ha!

**Comment by niftylettuce** [comment]
Any idea how to patch vim-autoformat filename?  Not sure how globby completely works, but couldn't I just make the file path be the tmpdir + remainder of file path?  This also affects eslint with vim-autoformat probably.

**Comment by niftylettuce** [comment]
figured it out, I'll need to use vim `:echo expand("%:p:h")` output to set the file path for tmp file

**Comment by niftylettuce** [comment]
@sindresorhus see <https://github.com/Chiel92/vim-autoformat/pull/206/commits/59bef54f5e8037d0b99536ac3479963776abf047>

**Comment by kevva** [comment]
Happy that you got it working in the end :).
