### ISSUE TITLE
Local space/tab settings being overriden by plugin

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/xo#252]
I hope I'm right in assuming that all local settings should take precedence over plugins, extends, etc. if that is the case then I've found a bug.

In [lass](https://github.com/lassjs/lass) we use the prettier plugin and part of that plugin handles indentation. `xo --fix` doesn't fix the indentation/spacing issue when we have the plugin config added even if we change our config to `"spaces": 6` for example. Yet as soon as we remove the plugin block we can run `xo --fix` and it changes all the spaces over to the specified amount.

If this isn't a bug could you please point us in the right direction to get this working.

Ref: https://github.com/lassjs/lass/pull/9

**Comment by kevva** [comment]
`prettier` overrides any conflicting rules AFAIK. From their [readme](https://github.com/prettier/eslint-plugin-prettier):

> The rule is autofixable -- if you run `eslint` with the `--fix` flag, your code will be formatted according to `prettier` style.
