### ISSUE TITLE
How about a shared config for the 'import' plugin setup?

### ISSUE THREAD

**Issue by lsunsi** [sindresorhus/xo#255]
I was 'building xo by hand' in eslint. 'react' has a config, and 'unicorn' just uses the recommendations. How about 'import'?

**Comment by sindresorhus** [comment]
React is a separate config as it's not bundled in XO. And `unicorn` just uses the defaults. I don't have time or interest in having the `import` config outside XO. Too much overhead. I'll move the `import` config to `eslint-config-xo` when https://github.com/eslint/eslint/issues/3458 is resolved.
