### ISSUE TITLE
Add .tslint support

### ISSUE THREAD

**Issue by userpixel** [sindresorhus/xo#26]
We use TypeScript instead of ECMA 6 and mainly rely on tslint: https://github.com/palantir/tslint
However we have some .js files and it can be cool to have one tool to take care of consistency.

**Comment by markogresak** [comment]
xo is based on [eslint](http://eslint.org/). It's meant for linting js and there is [no plan for ts support](https://github.com/eslint/eslint/issues/2446) (first response).
You should set up a build step (npm script, gulp, grunt, etc.) to lint js and ts files with xo and tslint, respectfully.

**Comment by kevva** [comment]
I don't see this happening.

**Comment by sindresorhus** [comment]
Yeah, not something I'm interested in supporting.

**Comment by cecilphillip** [comment]
Looks like eslint is considering TS support  https://github.com/eslint/typescript-eslint-parser
