### ISSUE TITLE
Problem with xo --init

### ISSUE THREAD

**Issue by clemtrek** [sindresorhus/xo#260]
When I run **xo --init** from the cli, It changes the indentation of the package.json. I have to manually recorrect it.

I checked it quite a few times and it happens everytime

**Comment by sindresorhus** [comment]
This is fixed in master already and will be part of the next release.

**Comment by clemtrek** [comment]
I am a student of class 9 and want some help in creating a module.
Would You Please Help

**Comment by clemtrek** [comment]
Kindly Tell Me When Do You Plan To Release It

**Comment by clemtrek** [comment]
Kindly tell me when do you plan to release
