### ISSUE TITLE
To to disable import/no-unassigned-import?

### ISSUE THREAD

**Issue by pavelpichrt** [sindresorhus/xo#262]
Hello, 

I am importing a dependency that doesn't need a named variable (a polyfill - core-js/es6/weak-map) and I need to disable the aforementioned rule. I tried all permutations of override as documented in the readme, however, nothing works:

Examples (I understand I don't need both global and override rule, this is just to illustrate, what I tried so far): 
```javascript
"xo": {
    "esnext": true,
    "import/no-unassigned-import": 0, // + all permutations, like an array syntax etc.
    "overrides": [
      {
        "files": "index.js",
        "import/no-unassigned-import": 0 // + all permutations
      }
    ]
  },
```

Thanks

**Comment by sindresorhus** [comment]
Per the docs, you have to place it in the `rules` option.

**Comment by pavelpichrt** [comment]
Thanks, this worked. For anyone else with the same issue (this want's clear to other devs in the office either), the correct syntax to override a rule is following (in package.json): 
```
  "xo": {
    "rules": {
      "import/no-unassigned-import": 0
    }
  }
```

**Comment by maxfi** [comment]
Not wanting to hijack this question but rather expand upon it...

In meteor it's common to do `import './some-template.html'`but this causes an `Imported module should be assigned import/no-unassigned-import` error.

I've already got a rule override for this rule to allow meteor packages (with only side-effects) to work:

```
// package.json

{
  "xo": {
    "prettier": true,
    "semicolon": false,
    "space": 2,
    "settings": {
      "import/resolver": "meteor"
    },
    "rules": {
      "import/no-absolute-path": 0,           // should be handled by eslint-import-resolver-meteor
      "import/no-unassigned-import": ["error", {
        "allow": ["meteor/*:*"]               // this allows: `import 'meteor/meteorhacks:unblock'`
      }]
    }
  }
}
```

I was hoping to simply add `*.html` to the allow section (`"allow": ["meteor/*:*", "*.html"]`) but it still throws the same error. Any ideas?

**Comment by dobromyslov** [comment]
@maxfi thank you for the best solution. I use it to import `reflect-metadata` package.
