### ISSUE TITLE
Enforce rules based on "engines" field in package.json

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#266]
So if for example, Node.js 8 is targeted we could enable some useful Node.js 8+ rules.

I've been wanting to enable some rules, but I don't want to introduce yet another option for it and be forced to use it in every repo. 

If there's no `"engines"` field in the project package.json, we will just default to how it works now.

It should also be possible to turn this off with an option for use in other environments.

Some things I'd like to enable:

- https://github.com/sindresorhus/eslint-config-xo/blob/891eb4c9bd1e33af8a12fd6f64d0629c08b88785/esnext.js#L15-L24
-
 https://github.com/sindresorhus/xo/blob/8ac0f3e25426937ef96288dfbe7d4dfda857c9bf/config/plugins.js#L33-L34
- https://github.com/sindresorhus/eslint-plugin-unicorn/pull/115
- And probably more in the future.

**Comment by sindresorhus** [comment]
> About situations where engines.node is not defined in package.json, shouldn't xo produce a warning or even error if it's omitted?

Warning

> xo could add a backports: true setting for people who want new rules to be enabled by semver-minor releases of xo. The backports rules could be declared in a way that they can easily be switched on by default during semver-major release.

Nah. I think that's overcomplicating it.

> A similar check that might be nice is no-legacy-backport-modules. For example directly depending on or requiring the object-assign module with engines.node >= 4 is likely pointless.

Sounds like a potential rule for https://github.com/mysticatea/eslint-plugin-node

> Eventually I'd like to see xo able to report an error if a module has dependencies that require a higher version of node. Say I have a module that requires node >=0.10 and run ncu -u to update all dependencies. This updates pify from 2.3.0 to 3.0.0 which is an unsupported module for node <4.

Sounds like a useful rule for https://github.com/mysticatea/eslint-plugin-node or https://github.com/benmosher/eslint-plugin-import You should open an issue about it there.

**Comment by coreyfarrell** [comment]
For now I've opened npm/node-semver#228.  Any rule comparing the `engines.node` range between multiple packages will require this.
