### ISSUE TITLE
support for class static properties

### ISSUE THREAD

**Issue by maticzav** [sindresorhus/xo#273]
Hi, 
I saw that there's an already closed issue #161 , with very similar problem. Is it possible to pull this off now? 🙂 
```jsx
class Signin extends React.Component {
   static propTypes = {
      foo: PropTypes.string
   }
   ...
}
```
> I am still getting `propTypes` is not defined.
```
  "xo": {
    "parser": "babel-eslint",
    "extends": "xo-react",
    "esnext": true,
    "semicolon": false,
    "space": 3,
    "rules": {
      "unicorn/filename-case": "off",
      "react/prop-types": "off",
      "import/prefer-default-export": "off",
      "object-curly-spacing": [
        "error",
        "always"
      ],
      "new-cap": "off"
    },
    "settings": {
      "import/resolver": {
        "babel-module": {}
      }
    }
  }
```

**Comment by sindresorhus** [comment]
It should work if `babel-eslint` has support for it.

---

Tip: You don't have to specify `"esnext": true,`. It's the default now.

**Comment by maticzav** [comment]
Thank you for the tip. 

Yes, I can see now, that it's a bug in `babel-eslint` hope it gets fixes, anyway thank you! 😄
