### ISSUE TITLE
Add package.lock or similar

### ISSUE THREAD

**Issue by rpadovani** [sindresorhus/xo#274]
This morning my builds are broken because a dependency of yours released a new version, my runner took it and xo doesn't work anymore.

I manually added to my package.json an old version of the dependency.

Please see https://github.com/mafintosh/is-my-json-valid/issues/149

**Comment by LinusU** [comment]
Hi 👋 

I was the one who published the broken is-my-json-valid 🙈 sorry about that!

A new version was published shortly after, and the broken one have been deprecated on npm.

For the record, I don't think that adding package-locks to `xo` is the way to solve this, rather I think that every end user of any project should have either a `package-lock.json`- (comes automatically with npm 5) or `yarn.lock`-file (comes with yarn, any version). That way the packages in that project will always be locked to a specific version, without having to rely on anyone else for that.

Also, if all your libraries added lock-files, you would probably end up with a lot of duplicate installations of different libraries at different patch versions; and when you find a bug you cannot yourself regenerate a lockfile with the proper package patched.

**Comment by rpadovani** [comment]
@LinusU interesting indeed.

I usually have `package-lock.json` in the main project. Problem is that I was working on a PC with npm3, so I installed xo (and your package consequently) and I did not update the lock file. It worked locally but then it failed on a runner, because you published a new version. Just a very bad timing :-)

`Also, if all your libraries added lock-files, you would probably end up with a lot of duplicate installations of different libraries at different patch versions`

This is indeed a problem, but I think there should be same way to freeze down the tree to the minor version. In your package, for example, you bumped the minor, so I don't think a build should break because a minor is bumped.

I also strongly believe in reproducibility of builds, so I think also patch version should be locked, but I understand this is not a so common opinion.

**Comment by LinusU** [comment]
> This is indeed a problem, but I think there should be same way to freeze down the tree to the minor version. In your package, for example, you bumped the minor, so I don't think a build should break because a minor is bumped.

This can be accomplished by using `~` in your package.json instead of `^`, then it will only update patch versions.

> I also strongly believe in reproducibility of builds, so I think also patch version should be locked, but I understand this is not a so common opinion.

I totally agree, which is why everyone should use `package-lock.json`, unfortunately there are still some maintained versions of Node shipping with an older version of npm, as I believe you ran into, but hopefully this will occur less and less 👍

**Comment by rpadovani** [comment]
> This can be accomplished by using ~ in your package.json instead of ^, then it will only update patch versions.

True. The problem here is `is-my-json-valid` is not a dependecy of xo - so probably I should go down all the tree and report to every project to use `~` instead of `^`. Probably I will :-) 

Thanks again for the fast fix and the time to discuss about it!

**Comment by LinusU** [comment]
> True. The problem here is is-my-json-valid is not a dependecy of xo - so probably I should go down all the tree and report to every project to use ~ instead of ^. Probably I will :-)

Ah, right, of course. I would actually strongly recommend _against_ doing that for a few reasons. 1) I don't know of any package author that backports bug fixes to earlier minor versions so you'll likely miss out on any bug fixes as soon as a minor release is published, and 2) you'll end up with more duplicated dependencies than you need for the same reason as with exact versions.

Finally, 3) with a package-lock.json file there is no need to lock in that anyway, so I believe that the proper fix is to simply use a lock file in your project. The good thing with that approach is that it's available today, and you don't have to rely on anyone else to do any changes to their projects 🚀 

> Thanks again for the fast fix and the time to discuss about it!

No problem 🍻

**Comment by sindresorhus** [comment]
Adding a package-lock.json here wouldn't help you as package-lock.json only applies when you run `npm install` in a project, not when you install XO from npm.
