### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#28]
Someone needs to do a Syntastic plugin.

https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide

**Comment by arthurvr** [comment]
There we go: https://github.com/arthurvr/syntastic/commit/289983577a9d7e0a1959da39d13c6f04f5d63022. Just gonna run it locally for a few days before doing the PR as I feel like I've missed some more edge cases.

**Comment by arthurvr** [comment]
(Some more people to test it definitely welcome!)
