### ISSUE TITLE
Help: Config Creation

### ISSUE THREAD

**Issue by F1LT3R** [sindresorhus/xo#294]
What is the best way to go about generating my own config? We would like to use one config across multiple projects in the same company.

**Comment by sindresorhus** [comment]
You can create a [shareable config]()https://eslint.org/docs/developer-guide/shareable-configs and use the `extends` option.

**Comment by F1LT3R** [comment]
Thanks, @sindresorhus!

**Comment by F1LT3R** [comment]
Will I still be able to control things inside `unicorn/filename-case` and `import/no-extraneous-dependencies`, etc. an ESLint sharable config?

Example rules from `package.json`:

```json
  "xo": {
    "esnext": true,
    "semicolon": false,
    "globals": [
      "it",
      "describe",
      "beforeEach",
      "before",
      "after",
      "afterEach",
      "__dirname"
    ],
    "rules": {
      "import/no-extraneous-dependencies": 0,
      "import/no-dynamic-require": 0,
      "import/no-unresolved": 0,
      "new-cap": 0,
      "no-use-extend-native": 0,
      "no-multi-str": 0,
      "space-before-function-paren": 0
    },
    "overrides": [
      {
        "files": "Toolconf.js",
        "rules": {
          "unicorn/filename-case": [
            "error",
            {
              "case": "pascalCase"
            }
          ]
        }
      },
      {
        "files": "**/Toolconf.spec.js",
        "rules": {
          "unicorn/filename-case": 0
        }
      }
    ]
  }
```

**Comment by sindresorhus** [comment]
> Will I still be able to control things inside unicorn/filename-case and import/no-extraneous-dependencies, etc. an ESLint sharable config?

Yes

**Comment by F1LT3R** [comment]
Fantastic, thanks.
