### ISSUE TITLE
How to integrate ESLint plugins?

### ISSUE THREAD

**Issue by rafaelrinaldi** [sindresorhus/xo#30]
I was just wondering the best way to integrate ESLint plugins to XO.

Let's say I want to use [`eslint-plugin-no-use-extend-native`](https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/) along with XO, what should I do? Does XO simply invokes ESLint and things work as expected or is there any trick that I need to do?

**Comment by sindresorhus** [comment]
I don't have a story for that yet unfortunately, but I'm planning to include that plugin by default in the next release.

**Comment by rafaelrinaldi** [comment]
Maybe having a 'plugins' key on the configuration could be a good idea?

Anyway, thanks for the answer.

--  
Rafael Rinaldi
http://rinaldi.io
