### ISSUE TITLE
npm package depend on github

### ISSUE THREAD

**Issue by yinrong** [sindresorhus/xo#31]
When I install some npm packages, there are messages like:

npm ERR! git fetch -a origin (git://github.com/sindresorhus/xo.git) fatal: read error: ...

Please don't access anything other than NPM registry. Since NPM is not only used in Internet, but also in some private network where there is no access to github.

**Comment by sindresorhus** [comment]
It only depends on itself from GitHub as a dev dependency (for reasons as npm packages can't normally depend on itself). That is only installed when you run `npm install` in the repo, not when you install from npm.

**Comment by joakimbeng** [comment]
@sindresorhus what's the reason for not having `"test": "node cli.js && ava"` and removing the `devDependency`?

**Comment by sindresorhus** [comment]
@joakimbeng I want to use a published version so I'm sure I use something stable.

**Comment by joakimbeng** [comment]
@sindresorhus alright, I see :)

**Comment by yinrong** [comment]
Thanks for attention. Some company just forbid github which makes anything depend on this package unusable. Hope this can be fixed
