### ISSUE TITLE
Open files with problems

### ISSUE THREAD

**Issue by oskarrough** [sindresorhus/xo#38]
While not directly related to xo, is there a way to open all files with problems found by xo,

`xo app/**/*.js | subl *`

… or something like that?

**Comment by sindresorhus** [comment]
Interesting. Hadn't thought of this. I'll think about adding something like `git diff --name-only`, but in the meantime you can use `xo --compact | cut -d ':' -f 1 -s | uniq | xargs subl`.

Might be useful to output the following format:

```
/Users/sindresorhus/dev/pageres/lib/index.js:1:6
/Users/sindresorhus/dev/pageres/lib/util.js:5:15
```

As `subl` and probably other tools support the line:column format:

```
Filenames may be given a :line or :line:column suffix to open at a specific
location.
```

**Comment by vdemedes** [comment]
What about using `$EDITOR` environment variable in a combination with a CLI flag (e.g. `--open`) to open failed files? Indeed a great feature!

```bash
$ EDITOR=atom # example value of $EDITOR
$ xo --open
```

**Comment by sindresorhus** [comment]
PR welcome :)
