### ISSUE TITLE
eslint env not working

### ISSUE THREAD

**Issue by ayhankuru** [sindresorhus/xo#4]
package json xo enviroment set, but not working

something this line broken [#L37-L49](https://github.com/sindresorhus/xo/blob/master/index.js#L37-L49)

**Comment by sindresorhus** [comment]
What does your package.json look like?

**Comment by ayhankuru** [comment]
![ekran goruntusu - 2015-08-03 02 34 18](https://cloud.githubusercontent.com/assets/2834954/9028625/27aaf5bc-3988-11e5-977d-5f2ed4c06cc9.png)

![ekran goruntusu - 2015-08-03 02 34 47](https://cloud.githubusercontent.com/assets/2834954/9028627/3a4fea6a-3988-11e5-9e06-0ac2f37224a2.png)

**Comment by ayhankuru** [comment]
also ```xo --env=mocha``` working but ```xo --env=mocha,es6``` this fail

![ekran goruntusu - 2015-08-03 02 37 17](https://cloud.githubusercontent.com/assets/2834954/9028638/930a5b22-3988-11e5-8357-13ac336b4262.png)

**Comment by sindresorhus** [comment]
Fixed in 0.4.4.

> xo --env=mocha,es6

Btw, that's invalid. Follow the description: `[Can be set multiple times]`:

```
xo --env=mocha --env=es6
```

**Comment by ayhankuru** [comment]
@sindresorhus sorry, thanks for patch :+1:
