### ISSUE TITLE
async/away throwing error... sometimes

### ISSUE THREAD

**Issue by dylang** [sindresorhus/xo#44]
This file passes:

https://github.com/sindresorhus/ava/blob/master/test/fixture/async-await.js

But if I copy it to the root of the project it fails:

<img width="569" alt="screen shot 2015-10-23 at 7 36 49 am" src="https://cloud.githubusercontent.com/assets/51505/10691670/f765b340-7958-11e5-9de9-ab16c60ba14c.png">

Line 5:
```js
test('async function', async function (t) {
```

If I take out that test, we get `Parsing error: Unexpected identifier` for the next test on this line:

```js
test('arrow async function', async t => {
```

I didn't see any special `eslint`/`xo` settings in this project or `ava`, such as an automatic *ignore* for `/fixtures`.

This might be related to https://github.com/sindresorhus/ava/issues/92, or visa versa.

**Comment by sindresorhus** [comment]
You have to use the `esnext` flag to use async functions.

**Comment by dylang** [comment]
I just saw this in XO 0.10 readme update, fixtures are ignored by default, so that's probably why `async/await` passes in fixtures but not when the file is copied to the root of the project.

https://github.com/sindresorhus/xo/blob/7644b9d9faf517b5b8f049b2083f13e7a803596c/index.js#L12-L21

**Comment by dylang** [comment]
Thanks @sindresorhus! I should have looked at the docs!
