### ISSUE TITLE
Appropriate formatter

### ISSUE THREAD

**Issue by g-div** [sindresorhus/xo#46]
Does an appropriate formatter for the rules defined in ```xo``` already exist ?

Something like [standard-format](https://github.com/maxogden/standard-format) for [standard](https://github.com/feross/standard).

**Comment by sindresorhus** [comment]
Yes, `$ xo --fix`.

**Comment by g-div** [comment]
Sorry, I've readed about the ```--fix``` option just right now (too late), but it doesn't seem to fix all problems found.

For example running ```xo --esnext --fix``` on the following file
```
let a = {
 	b: 1
};

exports.a = a;
```
Where this problem is:
``` 
2:2  error  Mixed spaces and tabs                       no-mixed-spaces-and-tabs
```
Will increment the indentation of the line 2 like this:
```
let a = {
 			b: 1
};

exports.a = a;
```

**Comment by sindresorhus** [comment]
Not all ESLint (what XO uses underneath) rules have fix ability yet, but it's improving for every release.
