### ISSUE TITLE
Rules not being overridden?

### ISSUE THREAD

**Issue by adjavaherian** [sindresorhus/xo#49]
I'm checking parity between xo and eslint warnings and I get 58 warning / errors with xo and 1 with eslint. Obviously, most of these are because xo has its own rules.  I'd like to override all of these with my own rules from my shareable config, but can't seem to get that to happen, even individual rules are not being overridden when I use my custom shareable config. 

```javascript
//package.json

  "xo": {
    "envs": [
      "node",
      "mocha"
    ],
    "extend": "myConfig",
    "rules": {}
  }
```

can I nullify the rules, like above?

Thanks!

**Comment by sindresorhus** [comment]
You can't nullify the default rules, only extend. The whole point of using XO is embracing most if not all the rules, and override the ones you don't agree with. If you want to replace all the rules you're probably better of just using ESLint directly.

As for: 

> but can't seem to get that to happen, even individual rules are not being overridden when I use my custom shareable config.

That should be working. It's tested here: https://github.com/sindresorhus/xo/blob/c8283cd0df59a9a8ef57b74033cf0184d2a0b735/test/api.js#L43

**Comment by adjavaherian** [comment]
Gotcha, Thanks Sindre.  Not sure what I was doing wrong, I'll figure it out.
