### ISSUE TITLE
Fix doesn't fix all fixable issues

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/xo#50]
Fix is awesome but it doesn't add e.g. trailing commas or fix indentation. I presume these need to be fixed in the eslint plugins? Any hints?

**Comment by sindresorhus** [comment]
Yes, it doesn't fix all issues yet. You can see the ones that are fixable here: http://eslint.org/docs/rules/ (they have a `(fixable)` at the end. ESLint are happy to accept PRs to add fixing for any rule missing.
