### ISSUE TITLE
Enable `globalReturn` in Node Environment.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/xo#51]
It is relatively new:

See: https://github.com/eslint/eslint/issues/1158

**Comment by sindresorhus** [comment]
Wouldn't help: https://github.com/sindresorhus/eslint-config-xo/commit/fc08f1034047ec02e150e48f8fe5468341bc4bc1

The reason you can return top-level in node modules is that they're wrapped by the Node.js runtime in an IIFE. With ES2015 modules they're actually on the top-level where `return` is not allowed. Not returning even though it's allowed is probably more future proof. I have been annoyed at not being able to `return` in CLI's many times though, so I'm happy to look into this again, but I think the [`modules` option](https://github.com/sindresorhus/eslint-config-xo/blob/5bd7ad6bd99710c7cec0ed3a5c10ceaab34ce745/index.js#L5) makes it not work.

**Comment by jamestalmage** [comment]
>  I think the modules option makes it not work.

That appears to still be true.

I say punt until `eslint` moves to the new acorn-based version of Espree. I believe `acorn` has better options for disabling this.

Ideally `eslint` would automatically detect your module type and allow/dis-allow this accordingly.

**Comment by sindresorhus** [comment]
We now use Babel as the parser and seems it's not that strict and allows return even in `modules`. So this is effectively fixed for now.

**Comment by novemberborn** [comment]
> We now use Babel as the parser and seems it's not that strict and allows return even in modules. So this is effectively fixed for now.

Not anymore: <https://github.com/sindresorhus/xo/commit/04733f1724a74c494458754d4982de53cdc30eeb>. This is an issue with AVA now.

**Comment by sindresorhus** [comment]
@novemberborn It's annoying indeed, but it's more spec compliant. `return` is not allowed top-level. The reason it works in Node.js is that each CommonJS module is wrapped in an IIFE. I plan on proposing allowing top-level return in JS, but haven't had the time.
