### ISSUE TITLE
Use of react plugin

### ISSUE THREAD

**Issue by Uhsac** [sindresorhus/xo#52]
Hello,

Sorry for this (maybe stupid) question but if I want to use react plugin did I need to `npm install eslint-config-xo-react xo` ? Or just `npm install xo` is sufficient ?

Thanks :)

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/eslint-config-xo-react/commit/46c6e3d60fcd6c5ea1fcdaea823a5f21fe4895b6

**Comment by Uhsac** [comment]
Perfect ! thanks
