### ISSUE TITLE
Consider tweaking `no-unused-vars`

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/xo#6]
Currently `no-unused-vars` doesn't allow function arguments that isn't used. This is a problem when used for example with express which checks `fn.length` to determine what to do.

The following is considered an error:

```javascript
function (err, req, res, next) {
  res.status(500).send('An error occurred')
}
```

That's because it doesn't use the `next` argument. But if I would remove it express would no longer consider this an error handler.

While I do consider it bad to depend on `fn.length` the reality is that arguable to most used node.js library does it.

`no-unused-var` can be specified to allow unused arguments, without affecting the other functionallity:

```json
[ 2, { "vars": "all", "args": "none" } ]
```

**Comment by kevva** [comment]
I think this is a perfect example of where you should overwrite it in your `package.json`. I've never encountered this myself.

**Comment by LinusU** [comment]
That could probably be true, or even add an `eslint-ignore` to that line. I thought that this would be quite common thought with express being so popular.

**Comment by sindresorhus** [comment]
Yeah, no thanks.

**Comment by stevemao** [comment]
This is bizarre

**Comment by sindresorhus** [comment]
@stevemao Comments like yours are useless. If you're going to comment, make it worth my while by sharing some constructive opinions on the subject.

**Comment by markogresak** [comment]
I would like to add that ignoring all arguments defeats the purpose of this rule, it saved my ass from bugs many times. 
As of the example, `next` is usually called in the error handler so this doesn't happen. I honestly haven't encountered a scenario like this so I'm not sure if there is workaround for making express recognize it as a handler and in quick scan through the docs I haven't found anything useful either. 

One possible solution would be an jshint options comment. Or add some ignores for general cases, such as this one and other common callbacks. But this would probably turn out as 
![Just one case](http://www.commitstrip.com/wp-content/uploads/2015/04/Strip-If-forever-650-finalenglsih1.jpg)
[© CommitStrip](http://www.commitstrip.com/en/2015/04/07/just-an-exception-they-said/)

**Comment by stevemao** [comment]
```js
function (err, req, res, next) {
  res.status(500).send('An error occurred')
}
```
I don't think this is a good use case of arity sniffing
