### ISSUE TITLE
Ability to indent files

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/xo#60]
Right now, setting the style to tabs-not-spaces and running `xo --fix` will result in a mess of mixed tabs and spaces if there were spaces. You also need to run it multiple times, once for each level of tabs that needs fixing.

The reason is that the eslint fix simply fixes the "expected 1 tab indentation" errors which occur at every block indent.

I am not sure that eslint is equipped to handle the possibly correct fix, which is to give an error on each line that does not have the exact required number of tabs/spaces. This possible fix also impacts non-uniform indentation, so not sure if that's desirable

So possibly XO needs to help out a little with a whitespace conversion pre-run and a recursive run until all the whitespace errors are resolved.

**Comment by sindresorhus** [comment]
This looks related: https://github.com/eslint/eslint/issues/4274

**Comment by sindresorhus** [comment]
Was fixed in ESLint 3.6.0.
