### ISSUE TITLE
`no-use-extend-native` causing issues with fresh install - Windows 10

### ISSUE THREAD

**Issue by brandon93s** [sindresorhus/xo#61]
This is likely an issue with `no-use-extend-native` itself, but seeing as xo enables it by default (currently) I'm noting it here. 

![xo](https://cloud.githubusercontent.com/assets/4730164/11910572/ad8f05e6-a5c7-11e5-8c06-d6c8c46f12cd.png)

**Comment by sindresorhus** [comment]
// @dustinspecker

**Comment by sindresorhus** [comment]
Can you share some code that reproduces the issue?

**Comment by brandon93s** [comment]
Looks like this is my fault. I have `node_modules` in sub-directories. Ignoring the sub `node_modules` resolves the issues. My assumption is that it is blowing up when it encounters a non-js file, or a file that it cannot read - I haven't had the time to investigate fully.

We can probably close this one and move it to `no-use-extend-native` as it doesn't appear to be `xo` related after all.

Fixing additions:  

```
  "xo": {
    "ignores": [
      "**/**/node_modules/**"
    ]
  }
```

**Comment by brandon93s** [comment]
As a side-note, it may be beneficial to ignore all `node_modules` folders by adding the following to `DEFAULT_IGNORE`.
```
"**\node_modules\**
```

**Comment by dustinspecker** [comment]
Opened an issue at https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/issues/24. If you can provide any more info that would be awesome.
