### ISSUE TITLE
WebStorm usage example

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#67]
Could be adapted from this one: https://github.com/feross/standard/pull/345/files

Need help to adapt and ensure it's working from someone using WebStorm.

**Comment by jamestalmage** [comment]
Maybe I could split out some of https://github.com/jamestalmage/install-live-templates to automate some of this.

**Comment by jamestalmage** [comment]
I will be interested to see how much of an improvement it makes, Webstorm comes with an `EditorConfig` plugin. The `generator-nm` `.editorconfig` makes XO basically just work. Of course, I've been using it that way for a long time, there may be some change I had to make that I'm forgetting.

**Comment by sindresorhus** [comment]
https://github.com/jamestalmage/install-live-templates/issues/2

**Comment by tomByrer** [comment]
Status please?  One of my team's coders (the main actually coder) uses Webstorm, & he's open to using XO.

**Comment by jamestalmage** [comment]
I have tried to get it to work, but I've been unsuccessful. Their eslint plugin does not let you configure the command executed.

**Comment by sindresorhus** [comment]
You could follow https://github.com/feross/standard/blob/master/docs/webstorm.md and switch out `eslint-config-standard` with `eslint-config-xo`. I don't really use Webstorm, so can't help much there. Happy to accept a recipe contribution :)

**Comment by jamestalmage** [comment]
They do have a plugin API. Hundreds of plugins available. I've actually written a WS plugin before, and we could probably copy much if the existing eslint plugin.

**Comment by jamestalmage** [comment]
See https://github.com/jamestalmage/xo-with-webstorm for directions on setting it up with WebStorm. It is a bit more involved than with other linters, but works well once configured.
