### ISSUE TITLE
consistent-this break when preventing nested shadowing

### ISSUE THREAD

**Issue by SBoudrias** [sindresorhus/xo#7]
The `consistent-this` rule will throw in this case:

```js
obj.foo = function () {
  var self = this;

  return through.obj(function () {
    var stream = this; // can't use self here or we'll shadow our previous variable
  });
};
```

Looks like a pretty frequent pattern we encounter in node code.

We can probably work around the rule in a couple ways, but sometime it won't work to keep context or bind arguments.

**Comment by kevva** [comment]
Why doesn't `.bind()` work?

**Comment by SBoudrias** [comment]
As you can see in this case, we have two specific `this` context that are shadowed. It's not a matter of binding anonymous function.

**Comment by sindresorhus** [comment]
From the [rule docs](https://github.com/eslint/eslint/blob/master/docs/rules/consistent-this.md):

> If you need to capture nested context, `consistent-this` is going to be problematic. **Code of that nature is usually difficult to read and maintain and you should consider refactoring it.**

-

I personally never had such code, but happy to consider possible solutions. Is there maybe a way we somehow can improve the ESLint rule? That would be the optimal solution. This rule has actually been useful in many scenarios for me, so would be too bad to disable it.

**Comment by Qix-** [comment]
I've been running into this constantly since using XO; sure, you can change it in package.json, but the defeats the purpose.

Consistent-this means well *dogmatically*, but doesn't make sense *pragmatically*. Javascript was kind of made to be able to throw around a this context. You hinder functionality by enabling this option.

**Comment by Qix-** [comment]
Just ran into it again. It has legitimate uses, especially when designing frameworks.

**Comment by sindresorhus** [comment]
Agreed, removed. I'll do a new XO release tomorrow.

**Comment by Qix-** [comment]
:+1: thank you :bow:

<sup>super into emojis tonight for some reason</sup>
