### ISSUE TITLE
JSX ES6 Import Support

### ISSUE THREAD

**Issue by 5an1ty** [sindresorhus/xo#70]
If I have a JSX file importing a component from another file:

    import Menu from 'app/components/menu';

I seem to get the following error:

    "Menu" is defined but never used (no-unused-vars)

However I use it in my JSX:

    render() {
      return (
        <div>
          {this.state.loggedIn ? <Menu/> : null}
          {this.props.children}
        </div>
      );
    }

**Comment by kevva** [comment]
You have to use https://github.com/sindresorhus/eslint-config-xo-react.

**Comment by 5an1ty** [comment]
@kevva Does that mean this isn't and will never be pre shipped with XO? I thought the whole point was to avoid having to configure eslint?

**Comment by kevva** [comment]
@5an1ty, well that's just how ESLint (which xo uses under the hood works). It can supports the JSX syntax but not all the semantics.

**Comment by 5an1ty** [comment]
Seems you can just do this to enable the react plugin:

    "xo": {
      "plugins": [
        "react"
      ]
    }

**Comment by kevva** [comment]
Yes, but you need to install it first.
