### ISSUE TITLE
Local module workflow query

### ISSUE THREAD

**Issue by swirlycheetah** [sindresorhus/xo#72]
I've installed xo globally and then used `xo --init` to add xo as a local dependency to my project, as the documentation suggest.

However I'm having issues when referencing xo from within an npm run task, for example;

package.json
```
"scripts": {
  "lint": "xo *.js **/*.js --space"
}
```

When running`npm run lint` I'm receiving errors about various packages not being available, initially it was `eslint-config-xo`;

```
Error: Cannot read config package: eslint-config-xo
Error: Cannot find module 'eslint-config-xo'
```

I installed that as a development dependency but was then told;

```
Error: Cannot find module 'eslint-plugin-babel'
```

Which I installed, but then received an error message saying that `eslint-plugin-no-empty-blocks` cannot be found and this has continued indefinitely with various other eslint modules.

It doesn't feel right to have to add every eslint config module to my dev dependencies to allow xo to work locally. Am I doing something wrong?

**Comment by sindresorhus** [comment]
That sounds more like a problem with npm corrupting the install. Can you try upgrading to the latest version of Node.js and npm?

**Comment by swirlycheetah** [comment]
Sorry missed that, yeah will give it a go thanks!
