### ISSUE TITLE
no-unused-vars rule does not work with React components

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/xo#74]
Latest xo has problems with detecting usage of React components over the code (`no-unused-vars`). Even though components are used in code, xo reports them as `defined but never used`.

example.js:

```js
const React = require('react');

const Button = React.createClass({});

const Container = React.createClass({
	render: function () {
		return <Button />;
	}
});
```

package.json:

```js
{
  "scripts": {
    "test": "xo"
  },
  "devDependencies": {
    "xo": "^0.12.1"
  }
}
```

```
$ npm test
```

<img width="546" alt="screen shot 2016-01-16 at 12 27 31 pm" src="https://cloud.githubusercontent.com/assets/697676/12372117/8e341fb0-bc4c-11e5-9fec-707d95837017.png">

**Comment by sindresorhus** [comment]
Yes, [ESLint doesn't support React semantics](http://eslint.org/blog/2015/03/eslint-0.17.0-released/#changes-to-jsxreact-handling), only parsing JSX. What you want is https://github.com/sindresorhus/eslint-config-xo-react and https://github.com/yannickcr/eslint-plugin-react. I guess I could make that clearer in the readme.

**Comment by vdemedes** [comment]
Thanks! Yeah, that would be great. Because readme states JSX is supported by default, but it *kinda* isn't.

**Comment by sindresorhus** [comment]
@vdemedes JSX per its spec is, but React semantics is slightly different from what I can remember.
