### ISSUE TITLE
Cannot define `rules` in `overrides`

### ISSUE THREAD

**Issue by ambar** [sindresorhus/xo#75]
Config:

```json
"xo": {
  "overrides": [
    {
      "files": "src/**/*.spec.js",
      "rules": {
        "no-unused-expressions": 0
      }
    }
  ],
}
```

`foo.spec.js`：

```js
...
expect(checkbox.checked).to.be.false
```

Lint:

> error  Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by sindresorhus** [comment]
The `overrides` functionality is not released yet. Hopefully soon, though.
