### ISSUE TITLE
no-empty-labels was removed

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/xo#77]
`no-empty-labels` [was removed](https://github.com/eslint/eslint/pull/5129) from the latest ESLint in favor of `no-labels`.

Should be removed from XO whenever they release and we update.

**Comment by sindresorhus** [comment]
Yes. I'll go through all the changes when ESLint 2 is out.

**Comment by Qix-** [comment]
:+1:

**Comment by sindresorhus** [comment]
Fixed
