### ISSUE TITLE
Add option to use a custom parser

### ISSUE THREAD

**Issue by frederickfogerty** [sindresorhus/xo#8]
The first one that springs to mind is `babel-eslint` (for those ES2015+ features). Maybe something like this?

```
"xo": {
  "parser": "babel-eslint"
}
```

**Comment by sindresorhus** [comment]
I knew this request would come. I would much rather just switch to it by default, but need to check whether that would cause problems.

Would be really awesome if ESLint could just use Babel as it's parser: https://twitter.com/sebmck/status/629090684809703424

**Comment by joakimbeng** [comment]
:+1: I want this as well! Even better if it was the default for `xo --esnext`...

**Comment by sindresorhus** [comment]
@joakimbeng Yup, that's the plan. Happy to receive a PR. Otherwise I'll probably get to it in a week or so.

**Comment by joakimbeng** [comment]
@sindresorhus do you plan on having `babel-eslint` as the default parser even without `esnext` option? Because if not, wouldn't `babel-eslint` be installed even for those not using it?

**Comment by sindresorhus** [comment]
> do you plan on having babel-eslint as the default parser even without esnext option? 

No.

> Because if not, wouldn't babel-eslint be installed even for those not using it?

Yes, so?

**Comment by joakimbeng** [comment]
> Yes, so?

I was merely curious on how you would solve it, if that was the case ;) Now that I know it wont be an issue I could work on a PR if you haven't started working on it yet?

**Comment by sindresorhus** [comment]
Cool. I haven't had a chance to look into this, so a PR would much welcome :)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/xo/commit/5c79ee667808717a74af1eca6aec9ec39fe18ded
