### ISSUE TITLE
Fly XO?

### ISSUE THREAD

**Issue by lukeed** [sindresorhus/xo#80]
Not trying to shamelessly plug my own stuff, but would be nice to have [fly-xo](https://github.com/lukeed/fly-xo) included in the plugins section since there is one for fly-ava in AVA's.

If not, no problem :+1:

**Comment by sindresorhus** [comment]
Sure, of course. That section is for anything related, not just stuff made by me. Submit a PR adding it ;)

**Comment by lukeed** [comment]
Sounds good :tada: thanks
