### ISSUE TITLE
Document how to put cmd line switches in package.json

### ISSUE THREAD

**Issue by SteveALee** [sindresorhus/xo#85]
in the README:

<pre>
Tips
    Put options in package.json instead of using flags so other tools can read it.
</pre>

How do we do that? I can't see any examples

**Comment by SteveALee** [comment]
Oh I see, some of the switches has equivalent options - but often a different name.. Some don't :)

**Comment by sindresorhus** [comment]
It's all documented here: https://github.com/sindresorhus/xo#config The options that accept arrays are pluralized. CLI flags don't accept multiple args, so they aren't. I think it's pretty clear, but happy to consider specific suggestions for improvements.

**Comment by SteveALee** [comment]
No It's OK, I was looking for exact match in the text. Sorry for noise

**Comment by SteveALee** [comment]
PS - Am loving XO!
