### ISSUE TITLE
Unable to turn off cap-new rule

### ISSUE THREAD

**Issue by SteveALee** [sindresorhus/xo#86]
With the code 
<pre>
import Sentence from './Sentence'
const sentenceComponent = Sentence(sentenceSources)
</pre>

where sentence is a function

And this is my package.json

<pre>
 "xo": {
    "esnext": true,
    "semicolon": false,
    "space": 2,
    "envs": [
      "browser",
      "node"
    ],
    "rules": {
      "new-cap": 0,
      "comma-dangle": [2, "only-multiline"]
    }
  }
</pre>

I always get this error for 'Sentance' in VS Code. I am exiting and restarting code every time I change package.json

<pre>
A function with a name starting with an uppercase letter should only be used as a constructor. (babel/new-cap)
(alias) Sentence(sources: any): {
    DOM: any;
}
import Sentence</pre>

I have tried variations of the rule like.

<pre>
'new-cap': [0, {newIsCap: true, capIsNew: true}],
'new-cap': [2, {newIsCap: false, capIsNew: false}],
</pre>

**Comment by vdemedes** [comment]
Try setting "babel/new-cap" rule, instead of "new-cap".

```js
"rules": {
  "babel/new-cap": 0
}
```

**Comment by SteveALee** [comment]
result!

Thanks. I did wonder what the babel prefix was for but could not find such rules in the ESLinit web site.

**Comment by sindresorhus** [comment]
Reopening so I don't forget to better document this. It's a side-effect of using `babel-eslint`.

**Comment by SteveALee** [comment]
As a comment I occasionally got 2 errors at same time, one  with babel/ and one without.

Also in VC Code I often had to switch back to a file several timer before the errors showed. Might be a bug or might be me.

**Comment by sindresorhus** [comment]
`babel-eslint` is removed in master. Will do a release in the next few days.
