### ISSUE TITLE
Shouldn't globbing recurse directories?

### ISSUE THREAD

**Issue by wenzowski** [sindresorhus/xo#87]
Noticed in mattkrick/meatier#122 that `xo src/**/*.js` does not pick up all `.js` files in the `src` directory. Is this intended behavior? It is a little unexpected to have to `ls src/**/*.js | xo`.

**Comment by joakimbeng** [comment]
Try to wrap the glob pattern in quotes like this: `xo 'src/**/*.js'`. Otherwise your shell will do the glob expanding instead of XO.

**Comment by wenzowski** [comment]
That works, thanks @joakimbeng.

recurses:
- `xo 'src/**/*.js'`

recurses with duplicates:
- `ls src/**/*.js | xo`

doesn't recurse:
- `xo src/**/*.js`

Now why isn't my shell expanding properly?

```
$ shopt nullglob
nullglob       	off

$ shopt failglob
failglob       	off

$ shopt extglob
extglob        	off

$ shopt globstar
bash: shopt: globstar: invalid shell option name

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

And the answer is...I forgot to brew my own `bash` so I have `3.x` instead of the `4.x` necessary to support recursion via `globstar`.

Mystery solved.
