### ISSUE TITLE
If pragmatism then why not spaces instead of tabs?

### ISSUE THREAD

**Issue by alessioalex** [sindresorhus/xo#9]
Reading the FAQ you said that `standard` didn't pick the most popular style, but spaces are widely preferred over tabs. Can you make this switch so it can just be "the default standard"? :)

**Comment by sindresorhus** [comment]
That argument is regarding `standard` trying to be *the* code style. I have no such goal. I just made XO after my code style, but I still allow other options, like spaces, for pragmatic reasons so other people can use it too. The reality is that the JS community is just too diverse and opinionated to create one code style. My goal is just to make it easier for me and people wanting to use this code style (or spaces by setting the `spaces` option).

Any suggestions on how I can make that clearer?

**Comment by alessioalex** [comment]
Oh I see. That's perfectly fine, I was thinking that your goal was the same as `standard` (one to rule them all). I guess you can specify what you just posted here inside the readme somewhere.

**Comment by kevva** [comment]
> XO is more pragmatic and has no aspiration of being the style

The readme is pretty clear to me.

**Comment by sindresorhus** [comment]
@kevva Yup. I still want rework that paragraph though. Keeping this open until then.

**Comment by joakimbeng** [comment]
@sindresorhus I'm just curious. What choices do you think `standard` made wrong, i.e. what popular rules do they not follow do you mean? If it's only the semicolons there's [`semistandard`](https://www.npmjs.com/package/semistandard) for that...

**Comment by sindresorhus** [comment]
@joakimbeng I don't remember them all from memory, but it was at least semicolons, space after function name `function foo () {}`, lax use of braces. Good overview of differences between `standard` and XO rules here: https://github.com/feross/standard/issues/216#issuecomment-127569835 As you can see, XO is a lot stricter. My personal preference is strict non-ambiguous readable code.

**Comment by joakimbeng** [comment]
@sindresorhus thanks!
I'm with you on the strictness! Then I'm convinced, XO is the one I'll
stick to :)

@joakimbeng <https://github.com/joakimbeng> I don't remember them all from
memory, but it was at least semicolons, space after function name function
foo () {}, lax use of braces. Good overview of differences between standard
and XO rules here: feross/standard#216 (comment)
<https://github.com/feross/standard/issues/216#issuecomment-127569835> As
you can see, XO is a lot stricter. My personal preference is strict
non-ambiguous readable code.

—
Reply to this email directly or view it on GitHub
<https://github.com/sindresorhus/xo/issues/9#issuecomment-129368618>.<img
src="
https://ci5.googleusercontent.com/proxy/azG3WCNKH7v5skRgRqmJoqRPMZIU-rgdBiKjyUTTNtHvl-kfdJ5Z46WeF-6XysaDp2bQ_nTErZH7KYyQ9Z8439PZ9FDcTedGONMr-GkqUhw7W0Kwg2OdTPjqZ4HZFw2cMLQglrXAqsji7yxeh70SRK1CYVk51w=s0-d-e1-ft#https://github.com/notifications/beacon/ABXHt7rcx8eV5FkKxGfJwBC8ppfg1BYKks5omF0ZgaJpZM4FnZO-.gif
">

**Comment by therealklanni** [comment]
That space after function thing really bugs me. I just can't stomach `function myFunc () {}`, but I like the space when there's no name. `function () {}`. 

Just goes to show that Standard (while a great idea) is poorly executed, and there are just too many diverse opinions to have a standard on code style. Let's have standard on things that really matter.

Sorry for the rant!

**Comment by Qix-** [comment]
@joakimbeng the semi-colons thing is a big one for me personally. I want to know when a statement is finished; it adds a wee bit of cognitive load reading source, imo.

@therealklanni just being clear, there isn't a space after the name of a function; only the `function` keyword, which means a space between `function` and `()` in the event it's anonymous.

**Comment by therealklanni** [comment]
@Qix- I was referring to [Standard](https://github.com/feross/standard#rules):

> Space after function name `function name (arg) { ... }`

**Comment by Qix-** [comment]
@therealklanni Aha gotcha.

**Comment by sindresorhus** [comment]
I've improved the section on how it differs from Standard: https://github.com/sindresorhus/xo#why-not-standard
