### ISSUE TITLE
Unable to find no-empty-blocks plugin though npm says is loaded

### ISSUE THREAD

**Issue by SteveALee** [sindresorhus/xo#92]
Since updating my deps and re doing npm install I now get errors

```bash
$ npm list eslint-plugin-no-empty-blocks
brian@0.1.0 C:\projects\brian
└─┬ xo@0.13.0
  └── eslint-plugin-no-empty-blocks@0.0.2
```

```bash
> brian@0.1.0 lint C:\projects\brian
> xo ./client/src/js/**/*.js

Error: Failed to load plugin no-empty-blocks: Cannot find module 'eslint-plugin-no-empty-blocks'
Referenced from:
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.load (C:\projects\brian\node_modules\eslint\lib\config\plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (C:\projects\brian\node_modules\eslint\lib\config\plugins.js:138:21)
    at load (C:\projects\brian\node_modules\eslint\lib\config\config-file.js:470:21)
    at C:\projects\brian\node_modules\eslint\lib\config\config-file.js:369:36
    at Array.reduceRight (native)
```
part of package.json:
<pre>
"xo": {
    "esnext": true,
    "semicolon": false,
    "space": 2,
    "envs": [
      "browser",
      "node"
    ],
    "plugins": [
      "immutable"
    ],
    "rules": {
      "babel/new-cap": 0,
      "comma-dangle": [
        2,
        "only-multiline"
      ],
      "immutable/no-let": 2,
      "immutable/no-this": 2,
      "immutable/no-mutation": 2,
      "no-var": 2,
      "no-undef": 2,
      "no-param-reassign": 2
    }
  }
}
</pre>

**Comment by SteveALee** [comment]
Same with other plugins

* eslint-plugin-no-use-extend-native
* eslint-config-xo/esnext - This one can't be installed manually :(

**Comment by SteveALee** [comment]
npm 2.14.12
node 4.3.2

I installed with `npm install i -D xo` (note not global)

**Comment by jamestalmage** [comment]
Can you try reinstalling (`rm -rf node_modules` first)?

If that doesn't work, try reinstalling with `npm@3`.

**Comment by SteveALee** [comment]
I already did that. :(

I'll have to figure how to upgrade to npm@3. I guess it must be fairly easy. I want to keep node LTS

**Comment by jamestalmage** [comment]
`npm install -g node@latest`

**Comment by jamestalmage** [comment]
`npm install -g npm@latest`

**Comment by Qix-** [comment]
I really hope this isn't contingent upon the version of `npm`...

**Comment by jamestalmage** [comment]
Easy. I'm just troubleshooting, not a permanent fix.

**Comment by SteveALee** [comment]
oh dear it works fine on node 5.8.0 with npm 3.7.3

```bash
> brian@0.1.0 lint C:\projects\brian
> xo ./client/src/js/**/*.js


C:\projects\brian\client\src\js\components\App.js
   7:2   error  More than 1 blank line not allowed                       no-multiple-empty-lines
....
```

**Comment by SteveALee** [comment]
possibly related to #19 but I updated to latest eslint without any change in problem (after emptying node_modules)

**Comment by SteveALee** [comment]
also fails with node 4.4.1 and npm 2.14.20

**Comment by kahlil** [comment]
@SteveALee I would definitely recommend you move to npm v3.x.x.

**Comment by Qix-** [comment]
This is a problem. At my company we use npm@2 for example. You're cutting out a large portion of users with this. :/

**Comment by SteveALee** [comment]
I'd says something weird ids going on - it's just dependency resolution after all and should work with deep or maximally flat deps.

**Comment by jamestalmage** [comment]
I think the problem is here: https://github.com/sindresorhus/xo/blob/master/options-manager.js#L115

It should also check `__dirname`

**Comment by sindresorhus** [comment]
> It should also check __dirname

Why? Its config file is defined with an absolute path https://github.com/sindresorhus/xo/blob/42106ff01148a00c701936ecfd5897aaf8798597/options-manager.js#L33, so it should resolve fine.

**Comment by sindresorhus** [comment]
ESLint did some config resolving improvements in 2.6.0, so might be worth reinstalling XO (which would bring in latest ESLint) and see if the issue still exists.

**Comment by SteveALee** [comment]
I delete node_modules and reinstalled. No change unless use npm 3

**Comment by jamestalmage** [comment]
I just successfully used your config:

```
$ npm --version
2.14.2

$ node --version
v4.0.0

$ node_modules/.bin/xo --version
0.13.0
```

I wonder if this is somehow Windows related. Is somebody mishandling path separators somewhere?

**Comment by jamestalmage** [comment]
> I wonder if this is somehow Windows related. Is somebody mishandling path separators somewhere?

Links to [this](https://github.com/substack/node-resolve/issues/78) are right [in the eslint source](https://github.com/eslint/eslint/commit/4ecd45e549c8622a26f5b105dd43b7a2827cf942#diff-3ca2712fe1d95b19637e57eb1a8b3a5bR322)

I wonder if we need to update `resolve-from` to handle that.

**Comment by jamestalmage** [comment]
It appears [`resolve-from`](https://github.com/sindresorhus/resolve-from/blob/master/index.js#L10) already handles that problem.

I'm stumped.

@SteveALee - Can you create a minimal reproduction that fails for you and publish it to npm?

**Comment by SteveALee** [comment]
@jamestalmage ok will do. Though I have a hard deadline to deliver on 

Are you unable to reproduce? I could try to debug a but as well.

**Comment by jamestalmage** [comment]
I am unable to reproduce (I even fired up a Windows VM)

**Comment by SteveALee** [comment]
Desperate measures indeed! :)
Well I'll be using bash for Windows soon.

**Comment by jamestalmage** [comment]
> Well I'll be using bash for Windows soon.

:+1: - I'm really interested to see how that whole thing turns out.

**Comment by SteveALee** [comment]
Yeah, been waiting a long time !!! I was about to switch back to Ubuntu for my dev PC

So the problem turns out to be a clash on eslint versions. It only tasks the following 2 lines in package.json

```json
  "devDependencies": {
   "eslint": "^2.5.3",
   "xo": "^0.13.0"
```

whereas if the eslint line is missing eslint 2.6.0 is installed under XO

This was left over form when I was using eslint before device XO was a nice abstraction.

Sorry for the time waster!

**Comment by kahlil** [comment]
\o/ :smile:

**Comment by SteveALee** [comment]
Actually I also had this XO cofing entry which caused the same error after I removed the eslint dependency.  Immutable was not installed.

```json
    "plugins": [
      "immutable"
    ],
```

So perhaps the error message is one is a general problem

**Comment by jamestalmage** [comment]
@SteveALee - If you have a plugin specified in your XO config that is not installed, then you will get that error. That is expected. It lets you know there is something wrong in your config, or that you need to install something else. 

You shouldn't have to install any plugins that ship with AVA, but if you want to add some extra custom rules, you need to install them.

**Comment by SteveALee** [comment]
@jamestalmage What is TAVA?

**Comment by jamestalmage** [comment]
I meant XO. AVA is a testing framework.
