### ISSUE TITLE
How handle multiple configs in one project?

### ISSUE THREAD

**Issue by SteveALee** [sindresorhus/xo#93]
I have client and server subtrees in my project and with `eslint` could have separate `.eslintrc` files for each tree.

However `Xo` puts config in the `pckage.json` so that appears not to be possible.

Is there a solution? Or do I need to split in to 2 repos?

**Comment by sindresorhus** [comment]
Use the [config override](https://github.com/sindresorhus/xo#config-overrides) feature.

```json
{
  "xo": {
    "overrides": [
      {
        "files": "project1/**/*.js",
        "esnext": true,
        "space": 3
      },
      {
        "files": "project2/**/*.js",
        "esnext": false
      }
    ]
  }
}
```

**Comment by SteveALee** [comment]
Excellent, thanks.
