### ISSUE TITLE
JSX indent rules not overridden by `--space` flags 

### ISSUE THREAD

**Issue by sterpe** [sindresorhus/xo#95]
Hello @sindresorhus,

The `--space` flag doesn't override the spacing rules set by `eslint-config-xo-react` by default, when using the shareable config.  JSX still is being linted according to the tab rules in the shareable config.

I put together #94.  Which quickly overrides those two rules when spaces are generally overridden.

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/xo/pull/94/commits/e197b164e94a9884b6609ce33aa6fedfe1258e00.
