### ISSUE TITLE
different results between `$ xo` and `$ npm run xo` (+ the BOM mystery)

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/xo#96]
I have a strange problem. I have already [reported the problem to ESLint](https://github.com/eslint/eslint/issues/5766), but I can only reproduce this issue when using XO. I haven't been able to reproduce the issue using eslint outside the context of XO.

So, the backstory:

[ESLint strips the Unicode BOM character from a file before linting](https://github.com/eslint/eslint/issues/4878), which means, essentially, [ESLint ignores any Unicode BOM characters at the beginning of a file](https://github.com/eslint/eslint/blob/5685ff58d74cb2b7096bcfa1dfc6cae95c2a9278/tests/lib/util/source-code.js#L151), but when I run XO on a file that has these zero-width non-breaking spaces (BOM), XO sees them.

The strange part is, that XO is only working when I run XO outside of the NPM Scripts. 

Consider this file `utf8-bom.js` (which has a hidden Unicode BOM value):

```js
"use strict";
console.log("This file has [0xEF, 0xBB, 0xBF] as BOM.");
```

and this `npm script`:
```
"scripts": {
    "test": "xo"
  },
```

### Expected Behavior

If I run XO (or ESLint with XO's configuration) on the `utf8-bom.js` file (shown above), I expect see this output:

<pre>
  1:2   error  Strings must use singlequote      quotes
  3:13  error  Strings must use singlequote      quotes
</pre>

I should **not** see the ` no-irregular-whitespace` error, because ESLint removes BOM characters. **However**, if I run XO via npm scripts, and then run it again on the terminal (without npm scripts), I get two very different results, even though both commands should be running the exact same linting routine. 

### Behavior via NPM

If I run XO via the NPM script `$ npm run test`, I get no output at all. No errors, no warnings; no output whatsoever.

### Behavior via terminal

If I run xo on the terminal with `$ xo`, I get the following output:

<pre>
/Users/michael/gitprojects/eslint-bom-test/utf8-bom.js
  1:1   error  Irregular whitespace not allowed  no-irregular-whitespace
  1:2   error  Strings must use singlequote      quotes
  3:13  error  Strings must use singlequote      quotes

✖ 3 problems (3 errors, 0 warnings)
</pre>

### Screenshot

The screenshot below shows the difference in output (3 errors when I run `$ xo` and no errors via `$ npm run test`:

![capture](https://cloud.githubusercontent.com/assets/5614571/14226710/dd1bcbba-f8e1-11e5-86e6-584be16f16e4.png)

**So there are two mysteries at play here:**

1. XO is somehow ignoring ESlint's ability to ignore the Unicode BOM character, and
2. XO is yielding two different results between npm scripts and the terminal.

The reason why I feel this is an XO issue, and not an ESLint issue, is because I can't recreate the error when using straight ESLint.

This ESLint command:
```
$ eslint utf8-bom.js
```
yields the results I expect:

<pre>
/Users/michael/gitprojects/eslint-bom-test/utf8-bom.js
  1:1   error  Strings must use singlequote  quotes
  3:13  error  Strings must use singlequote  quotes
</pre>

If it helps, I have created [a small repo to demonstrate the problem](https://github.com/radiovisual/eslint-bom-test). Feel free to download these files if it helps you diagnose the problem.

**Comment by sindresorhus** [comment]
Wild guess, maybe it has something to do with us using the [`babel-eslint`](https://github.com/babel/babel-eslint) parser by default.

Can you try switching it to the default ESLint parser and see if it's still an issue?

https://github.com/sindresorhus/xo/blob/60fe4d69c88abeaecceb17b243e5cf80917b2975/config/overrides.js#L5

**Comment by radiovisual** [comment]
@sindresorhus , per your suggestion, I changed the parser to the `esprima` parser, and then I also tried leaving the `config/overides.js` file blank so that it returned an empty object (just to force the defaults), and in both situations I got the exact same result (same errors, or lack of errors) as I reported above.

**Comment by sindresorhus** [comment]
I tried cloning your repo, but I'm not seeing any `no-irregular-whitespace` with either `$ npm test` nor `$ xo`.

My last suggestion would be to ensure your global XO install is the latest version. Other than, try to `npm cache` and reinstal both global and local XO.

**Comment by radiovisual** [comment]
@sindresorhus , I took your advice, and I ran a few more tests. I was able to conclude that this error only appears in the `0.12.x` releases of XO, and doesn't seem to affect versions `0.13.x` and higher. 

So simply updating to the latest version of XO solves this problem. I think this is enough to close this issue, so I will go ahead and close it. If you disagree for any reason, please feel free to re-open. 

Thanks for your help.

👍
